### ISSUE TITLE
secret key should not be needed if not starting a leadership

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#110]
**Describe the bug**

the command line interface expects the private key (`--secret` option) even if we don't have a leadership node. This is an error and the CLI should be updated accordingly

**To Reproduce**

Steps to reproduce the behaviour:

1. use config:
   ```yaml
   bft:
     constants:
       t: 10
     leaders:
       - 482ec7835412bcc18ca5c1f15baef53e0d62092fe1bbf40ea30fac895fd0f98c3b009cfd62715a5b871aabf5d603bec5aa5c8b3eae537fb254dd83ef88950d7d
       - b77f6ed6edbb0a63e09764ccaf2bb6bb5cdc8e54ce1bab6aeccacb98848dfe01b77a9be9254a0f2d103953264df9b7957d8e61608b196723c109c28c89c1bb1e
   legacy_listen:
          - "127.0.0.1:8080"
   grpc_listen:
          - "127.0.0.1:8081"
   storage: "/tmp/storage"
   logger:
     verbosity: 7
     format: json
   ```
2. use any genesis file in the `cardano-deps/exe-common/genesis/*.json`
3. run `cargo run -- --genesis-config=cardano-deps/exe-common/genesis/5f20df933584822601f9e3f8c024eb5eb252fe8cefb24d1317dc3d432e940ebb.json --config=config.yml -vvvv --without-leadership```
4. see error:
   ```
   thread 'main' panicked at 'secret config unspecified', src/libcore/option.rs:1040:5
   ```

**Expected behavior**

Since we are not launching the leadership node we don't need a secret key.

**Additional context**

The secret key should be only mandatory if we are starting a leadership node (so `--without-leadership` should cancel the _mandatory-ness_ of the `--secret` option).
