### ISSUE TITLE
The `error!` log are not reported by default (early logging)

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#111]
**Describe the bug**

if the config file cannot be loaded properly jormundandr fails without giving a clue of the error.

**To Reproduce**

Steps to reproduce the behaviour:

   ```yaml
   bft:
     constants:
       t: 10
     leaders:
       - 482ec7835412bcc18ca5c1f15baef53e0d62092fe1bbf40ea30fac895fd0f98c3b009cfd62715a5b871aabf5d603bec5aa5c8b3eae537fb254dd83ef88950d7d
       - b77f6ed6edbb0a63e09764ccaf2bb6bb5cdc8e54ce1bab6aeccacb98848dfe01b77a9be9254a0f2d103953264df9b7957d8e61608b196723c109c28c89c1bb1e
   legacy_listen:
          - "127.0.0.1:8080"
   grpc_listen:
          - "127.0.0.1:8081"
   storage:
          - "/tmp/storage"
   logger:
     verbosity: 7
     format: json
   ```
2. use any genesis file in the `cardano-deps/exe-common/genesis/*.json`
3. create a secret key: `cardano-cli debug generate-xprv secret.key`
4. run `cargo run -- --genesis-config=cardano-deps/exe-common/genesis/5f20df933584822601f9e3f8c024eb5eb252fe8cefb24d1317dc3d432e940ebb.json --config=config.yml -vvvv --secret=secret.key```
5. see error (or absence of error)
   ```
   ```
6. see error code:
    ```
    > echo ${?}
    1
    ```

**Expected behaviour**

we should have an error message printed on the output:

```
error: storage: invalid type: sequence, expected path string at line 12 column 8
```

which state that the config.yaml, line 12 is invalid:

```yaml
storage:
       - "/tmp/storage"
```

indeed the correct shape should have been:

```yaml
storage: "/tmp/storage"
```

**Additional context**

might relate to #72
