### ISSUE TITLE
Neither delegatee nor delegator are getting rewards - 0.8.0-rc5

### ISSUE THREAD

**Issue by KtorZ** [input-output-hk/jormungandr#1271]
**Describe the bug**

What follows describes **two** issues.

I am running a self-node with 3 stake pools and the following incentive and rewards configuration:

```yaml
  total_reward_supply: 100000000000000
  reward_parameters:
    halving: 
      constant: 100
      ratio: "1/1"
      epoch_start: 0
      epoch_rate: 1

  treasury: 0
  treasury_parameters:
    fixed: 0
    ratio: "0/1"
``` 

Pools are configured to take no tax on rewards (neither fixed nor ratio). When I delegate to one of the stake pool:

- The transaction correctly appears in a block 

<details>
<summary>see details</summary>

```
- fragment_id: a7a19abf1bebf8d71316171b1d51ab7f8275f7fa5dc006a732827f534b01867f
  last_updated_at: "2019-12-03T18:37:41.010148961+00:00"
  received_at: "2019-12-03T18:37:39.762200860+00:00"
  received_from: Rest
  status: 
    InABlock:
      block: 1aacbc247954d776291a93d8cc4dddc107f2fac6d5b0c3443c7bf758d912a894
      date: "1919620.2"
```
</details>

- **[ISSUE 1]** the delegation activity is immediately reported on the corresponding account but the stake is only reported as being delegated **2 epochs** after the transaction has been inserted, whereas I'd expect it to be reported on the next epoch:

<details>
<summary>see details</summary>

`$ jcli rest v0 stake get`
```yaml
epoch: 1919621
stake:
  dangling: 0
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 1
    - - 345ccb86e4285fff73e01cc3dbc315243d2f3da2878e049fc6dcd4318c17829e
      - 1
    - - 494b7852eb34d39e0c46b5ced94d3e5b34dd70da225a38cc6dfd8a2af7dde9d7
      - 1
  unassigned: 0
```

```yaml
epoch: 1919622
stake:
  dangling: 0
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 99999999958
    - - 345ccb86e4285fff73e01cc3dbc315243d2f3da2878e049fc6dcd4318c17829e
      - 1
    - - 494b7852eb34d39e0c46b5ced94d3e5b34dd70da225a38cc6dfd8a2af7dde9d7
      - 1
  unassigned: 0
```

`$ jcli rest v0 account get ed25519_pk15xs...`

```yaml
counter: 0
delegation:
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 1
last_rewards:
  epoch: 0
  reward: 0
value: 0
```
</details>

- **[ISSUE 2]** No matter how long I wait, neither the stake pool nor the delegator get a reward. Note that I also tried to make an additional transaction after the delegation certificate was inserted and after the stake was reported as part of the pool's stake. The transaction is inserted, but no rewards.

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.8.0-rc5 (HEAD-cecea4d, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

2. `jormungandr --full-version` output;
jormungandr 0.8.0-rc5 (HEAD-cecea4d, release, linux [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
See the description above.

**Expected behavior**

- The stake is assigned to the pool on the epoch directly following the insertion of the delegation certificate.

- On the epoch were the pools is active:
    - The pool get a constant reward of 100 lovelace
    - The delegator gets a reward according to the tax parameters registered for that pool.

**Additional context**

In `rc4`, the pools used to get _some rewards_, although more than the constant reward set in the genesis configuration.

**Comment by KtorZ** [comment]
@NicolasDP, it seems that #1272 didn't fix the problem though it did something. 
The genesis parameters and the pool settings are still as described in the ticket. Here are the results of my last test (simply submits a delegation certificates to a registered pool)

## Epoch 1925061

- Delegation certificate submitted and in a block.
  - Fees are `43` coins.
  - Change output is a grouped address delegating `99999999957` coins to `712dd0286`

<details>
  <summary>jcli rest v0 message logs</summary>

```yaml
- fragment_id: a7a19abf1bebf8d71316171b1d51ab7f8275f7fa5dc006a732827f534b01867f
  last_updated_at: "2019-12-04T09:44:31.013602145+00:00"
  received_at: "2019-12-04T09:44:29.527614662+00:00"
  received_from: Rest
  status: 
    InABlock:
      block: 9558983165cbeeba12753cc76c91e997c5bc0591201d756d0b75339258f2b67e
      date: "1925061.2"
```
</details>

<details>
  <summary>jcli rest v0 stake get</summary>

```yaml
epoch: 1925061
stake:
  dangling: 0
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 1
    - - 494b7852eb34d39e0c46b5ced94d3e5b34dd70da225a38cc6dfd8a2af7dde9d7
      - 1
    - - 345ccb86e4285fff73e01cc3dbc315243d2f3da2878e049fc6dcd4318c17829e
      - 1
  unassigned: 100000000000
```
</details>


<details>
  <summary>jcli rest v0 account get ed25519_pk15xs80... </summary>

```yaml
counter: 0
delegation:
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 1
last_rewards:
  epoch: 0
  reward: 0
value: 0
```
</details>


## Epoch 1925062 (e0+1)

- Nothing happens.

<details>
  <summary>jcli rest v0 stake get</summary>

```yaml
epoch: 1925062
stake:
  dangling: 0
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 1
    - - 494b7852eb34d39e0c46b5ced94d3e5b34dd70da225a38cc6dfd8a2af7dde9d7
      - 1
    - - 345ccb86e4285fff73e01cc3dbc315243d2f3da2878e049fc6dcd4318c17829e
      - 1
  unassigned: 100000000000
```
</details>

<details>
  <summary>jcli rest v0 account get ed25519_pk15xs80... </summary>

```yaml
counter: 0
delegation:
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 1
last_rewards:
  epoch: 0
  reward: 0
value: 0
```
</details>

## Epoch 1925063 (e0+2)

- Some stake is being reported on `712dd028`. It matches the initial pool's stake plus the output of the stake delegation transaction. No activity on the account.
- No rewards.

<details>
  <summary>jcli rest v0 stake get</summary>

```yaml
epoch: 1925063
stake:
  dangling: 0
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 99999999958
    - - 494b7852eb34d39e0c46b5ced94d3e5b34dd70da225a38cc6dfd8a2af7dde9d7
      - 1
    - - 345ccb86e4285fff73e01cc3dbc315243d2f3da2878e049fc6dcd4318c17829e
      - 1
  unassigned: 0
```
</details>

<details>
  <summary>jcli rest v0 account get ed25519_pk15xs80... </summary>

```yaml
counter: 0
delegation:
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 1
last_rewards:
  epoch: 0
  reward: 0
value: 0
```
</details>

# Epoch 1925064 (e0+3)

- The pool's stake increases by `140`? Not sure what this value corresponds to.
  - Rewards are supposed to be flat of `100` coins
  - Transaction fees were equal to `43` coins
    - `42` fixed for the certificate
    - `1` fixed for the inputs/outputs
    - `0` inputs/outputs coefficient

- Still no rewards on the account. And not clear if the pool got a reward. Though, the
  account `last_rewards` now mention a reward of `0` lovelace got in this epoch?

<details>
  <summary>jcli rest v0 stake get</summary>

```yaml
epoch: 1925064
stake:
  dangling: 0
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 100000000098
    - - 494b7852eb34d39e0c46b5ced94d3e5b34dd70da225a38cc6dfd8a2af7dde9d7
      - 1
    - - 345ccb86e4285fff73e01cc3dbc315243d2f3da2878e049fc6dcd4318c17829e
      - 1
  unassigned: 0
```
</details>

<details>
  <summary>jcli rest v0 account get ed25519_pk15xs80... </summary>

```yaml
counter: 0
delegation:
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 1
last_rewards:
  epoch: 1925064
  reward: 0
value: 0
```
</details>

# Epoch 1925065 (e0+4)

- Pool's stake is increased by another `100` lovelace, seems to match the reward amount?
- The account still mentions a reward of `0` lovelace :shrug:

<details>
  <summary>jcli rest v0 stake get</summary>

```yaml
epoch: 1925065
stake:
  dangling: 0
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 100000000198
    - - 494b7852eb34d39e0c46b5ced94d3e5b34dd70da225a38cc6dfd8a2af7dde9d7
      - 1
    - - 345ccb86e4285fff73e01cc3dbc315243d2f3da2878e049fc6dcd4318c17829e
      - 1
  unassigned: 0
```
</details>

<details>
  <summary>jcli rest v0 account get ed25519_pk15xs80... </summary>

```yaml
counter: 0
delegation:
  pools:
    - - 712dd028687560506e3b0b3874adbd929ab892591bfdee1221b5ee3796b79b70
      - 1
last_rewards:
  epoch: 1925065
  reward: 0
value: 0
```
</details>

# Next epochs 

- The pool's stake doesn't move (as expected).
- The `last_rewards` epoch for the account keeps on increasing and reward remains `0` (expected I assume).
