### ISSUE TITLE
Rewards are not evenly distributed per stake pool based on the number of blocks created in an epoch - 0.8.0-RC10

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#1325]
**Describe the bug**
Rewards are not evenly distributed per stake pool based on the number of blocks created in an epoch - 0.8.0-RC10

**Mandatory Information**
```
jcli 0.8.0-rc10 (HEAD-73f68fc3, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
jormungandr 0.8.0-rc10 (HEAD-73f68fc3, release, windows [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
```

**To Reproduce**
1. update the value for `block0_date` to the current date (rewards are created only for first 183 epochs)
2. reencode block0/genesis_hash
3. start node1 - `jormungandr ---genesis-block block-0.bin --config node_config.yaml --secret node_secret.yaml`
4. start node2 - `jormungandr --config node_config.yaml --secret node_secret.yaml --genesis-block-hash f1ff6011d29a5d67127721806d9418bb872e2dc0b9716fe9e5bb520423399fc9`
5. wait for 1-2 epochs
6. start the attached script - `get_rewards.py`
7. wait for the script to finish and check the generated files - rewards_history.xlsx and rewards_history.txt

**Possible Issue**:
- the rewards_per_block are different for the stake pools inside the same epoch (details in the screenshot below + attached documents)
- ex: 
-- in epoch 3, stake pool 1 created 3 blocks and stake pool2 created 10 blocks
-- stake pool1 received rewords of 1534246576000  --> rewards per block created: 
511,415,525,333.33
-- stake pool=21 received rewords of 1917808220000 --> rewards per block created: 
191,780,822,000.00
--

**Expected behavior**
The rewards for the stake pools are offered based on the number of blocks created by a stake pool in the respective epoch.

**Additional context**
```
total_rewards = value_for_stakers + value_taxed       # per stake pool
rewards_per_block = total_rewards / no_of_created_blocks       # per stake pool
```
- the per stake pool rewards are taken from `jcli rest v0 stake-pool get`
- the no of blocks per epoch is calculated for the previous epoch (from tip)
- scenario: 2 local stake pool nodes connected together, 1 account per node acting both as owner and delegator for the stake pool

- node1 files:
[node1.zip](https://github.com/input-output-hk/jormungandr/files/3944615/node1.zip)

- node2 files
[node2.zip](https://github.com/input-output-hk/jormungandr/files/3944618/node2.zip)

- script 
[get_rewards.zip](https://github.com/input-output-hk/jormungandr/files/3944622/get_rewards.zip)

- generated files
[generated_files.zip](https://github.com/input-output-hk/jormungandr/files/3944628/generated_files.zip)
![Screenshot_1](https://user-images.githubusercontent.com/29144964/70526508-54c03a00-1b7c-11ea-9445-e558df352adb.png)

**Comment by dorin100** [comment]
trying to check it without the script, only for the current epoch

**Comment by dorin100** [comment]
theory confirmed by below:

```
pool_id
b2ff842e45c3665d098a0cf97e563dd85b7e60251a06a8bc16a0e1583b5c0de6    [50.36, 50.23, 50.1]                                  
dd879881832622786b2e14fbedadd5d050163e638b4a1a5830776af37d9ba207    [50.54, 50.42, 50.35, 50.28, 50.14, 50.10, 50.5, 50.2]
```
```

sp1 - 3 blocks
sp2 - 8 blocks

rewards_sp1 = 1035616432390 + 115068499610 = 1150684932000
rewards_sp2 = 2301369864000 + 0 = 2301369864000

rewards_per_block_sp1 = 1150684932000 : 3 = 383561644000
rewards_per_block_sp2 = 2301369864000 : 8 = 287671233000
```

```
jcli rest v0 stake-pool get b2ff842e45c3665d098a0cf97e563dd85b7e60251a06a8bc16a0e1583b5c0de6 --host "http://127.0.0.1:9001/api"
---
kesPublicKey: kes25519-12-pk1z6w54ydr42rsh6hles9k53a8xxsv5jgcw8cnkgxx7g4l8hupdcsqh7v2lh
rewards:
  epoch: 50
  value_for_stakers: 1035616432390
  value_taxed: 115068499610
```
```
jcli rest v0 stake-pool get dd879881832622786b2e14fbedadd5d050163e638b4a1a5830776af37d9ba207 --host "http://127.0.0.1:9002/api"
---
kesPublicKey: kes25519-12-pk1qagtp0fjt9v44wj7w0rhuycxua7wcw0dd4e5x728hz4trfksn7ss6dhdua
rewards:
  epoch: 50
  value_for_stakers: 2301369864000
  value_taxed: 0
```

**Comment by dkijania** [comment]
INFO: I've automated similar test in chain-libs:

https://github.com/input-output-hk/chain-libs/blob/master/chain-impl-mockchain/src/testing/e2e/rewards/mod.rs#L444

And it's passing.  One thing to note also that jormungandr is not referring to newest chain libs commit. so maybe this issue is fixed on newest master

**Comment by dorin100** [comment]
I reproduced it also on QA testnet today, using RC11 (both on local node and also on testnet)

```
Jcli rest v0 settings get --host "http://127.0.0.1:9000/api"
---
block0Hash: eb7e3169b6440c94962e495f2b6d6ae54799890e1d55bd04a526012c92bcb7d2
block0Time: "2019-12-10T16:39:53+00:00"
blockContentMaxSize: 1024000
consensusVersion: genesis
currSlotStartTime: "2019-12-11T06:11:03+00:00"
epochStabilityDepth: 10
fees:
  certificate: 10000
  coefficient: 100000
  constant: 200000
rewardParams:
  compoundingRatio:
    denominator: 1
    numerator: 0
  compoundingType: Linear
  epochRate: 1
  epochStart: 1
  initialValue: 3835616440000
slotDuration: 2
slotsPerEpoch: 750
treasuryTax:
  fixed: 0
  ratio:
    denominator: 10
    numerator: 1
```

- blocks per stake pool created in epoch 31 (got going backward from tip in epoch 32)
```
153ee4ad63404af12b1fea5840cea94a1bf1f8d5cbf6b0a5dd983661b3174a9    [31.617, 31.521, 31.504, 31.486, 31.434, 31.161, 31.155, 31.135, 31.116, 31.115, 31.112, 31.111]
220b3cab8542fe1ddb3070b71b2fc2c2e86ec20132ca41e21de11a90b05197c1    [31.674, 31.643, 31.616, 31.605, 31.586, 31.582, 31.560, 31.541, 31.532, 31.501, 31.374, 31.304, 31.256, 31.241, 31.174, 31.145, 31.41]
ab19d16565e9f42d006a1293d1e6f53af9385522bbcb6c4bdd250a03319a0f6e    [31.688, 31.669, 31.591, 31.563, 31.485, 31.471, 31.357, 31.216, 31.166, 31.123, 31.104, 31.26]
c9589185bbeb04ba030ef548e2e9e3adbcdb8ec32e074147c5db53318acdc0cc    [31.641, 31.599, 31.596, 31.567, 31.522, 31.490, 31.453, 31.411, 31.352, 31.296, 31.184, 31.171, 31.153, 31.89]
dbf95409bf991b2cb9a9afa143f2838f726b6d1950d487dbbf94d0743234da19    [31.553, 31.526, 31.370, 31.346, 31.324, 31.295, 31.247, 31.246, 31.239, 31.113, 31.92, 31.45, 31.40, 31.22]
f6d8250626497d56620d1435bff09bd4a850f0549c7dc620baf2c10f4f2cd6f4    [31.651, 31.612, 31.592, 31.535, 31.516, 31.505, 31.500, 31.441, 31.375, 31.363, 31.185, 31.124, 31.119, 31.62]

0153ee4ad63404af12b1fea5840cea94a1bf1f8d5cbf6b0a5dd983661b3174a9 - 12 blocks
220b3cab8542fe1ddb3070b71b2fc2c2e86ec20132ca41e21de11a90b05197c1 - 17 blocks
ab19d16565e9f42d006a1293d1e6f53af9385522bbcb6c4bdd250a03319a0f6e - 12 blocks
c9589185bbeb04ba030ef548e2e9e3adbcdb8ec32e074147c5db53318acdc0cc - 14 blocks
dbf95409bf991b2cb9a9afa143f2838f726b6d1950d487dbbf94d0743234da19 - 14 blocks
f6d8250626497d56620d1435bff09bd4a850f0549c7dc620baf2c10f4f2cd6f4 - 14 blocks
```

- rewards per stake pool - got at the beginning of the epoch using `jcli rest v0 stake-pool get`
![image](https://user-images.githubusercontent.com/29144964/70596293-1d06d000-1c18-11ea-947f-8da1e5282bbb.png)
[rewards_history.txt](https://github.com/input-output-hk/jormungandr/files/3948727/rewards_history.txt)
[rewards_history.xlsx](https://github.com/input-output-hk/jormungandr/files/3948728/rewards_history.xlsx)

- being a public testnet, I cannot see if there were multiple nodes competing for the same block/slot at any time.

- one thing I am not at peace with is that the rewards per current epoch are displayed at the beginning of the epoch and the effective no of blocks created by each node can be seen only at the end of the epoch; during the epoch, there might be slots where 2 or multiple nodes are competing for creating the block and I am not sure how the reward mechanism knows about the winner at the beginning of the slot.
