### ISSUE TITLE
Error while accepting connection on (IP) Os code: 22 kind: InvalidInput - Invalid argument task: network

### ISSUE THREAD

**Issue by rickymac68** [input-output-hk/jormungandr#1367]
**Describe the bug**
My jormungandr node ran fine for several hours after first building and starting it, then began crashing. Now it crashes every 5 or 10 minutes. Logs are below. I have RUST_BACKTRACE=full turned on but there is no BACKTRACE output upon the crash.

**Mandatory Information**
1. jcli 0.8.2 (HEAD-fe327f9a, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]
2. jormungandr 0.8.2 (HEAD-fe327f9a, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)]

**To Reproduce**
1. jormungandr is running in leadership mode

**Expected behavior**
no crash

**Additional context**
Dec 14 19:11:24.419 INFO incoming connection on 192.168.1.116:3100, peer_addr: 54.154.193.39:50808, task: network
Dec 14 19:11:24.427 INFO disconnecting client, node_id: 82751b5c5c42ea98599bb112374c245e5c7097537ae987f0, peer_addr: 78.46.204.19:3000, task: network
Dec 14 19:11:24.530 INFO incoming HTTP/2 connection error, reason: connection error: Connection reset by peer (os error 54), peer_addr: 54.154.193.39:50808, task: network
Dec 14 19:11:24.530 ERRO Error while accepting connection on 192.168.1.116:3100: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }, task: network
Dec 14 19:11:24.539 INFO service finished with error, task: network
Dec 14 19:11:24.539 CRIT Service has terminated with an error
A service has terminated with an error
Jormungandr crashed with exit code 12. Respawning..
Dec 14 19:11:25.747 INFO Starting jormungandr 0.8.2 (HEAD-fe327f9a, release, macos [x86_64]) - [rustc 1.39.0 (4560ea788 2019-11-04)], task: init
Dec 14 19:11:25.749 INFO storing blockchain in '"./storage/blocks.sqlite"', task: init

---------------
I tried various node-config.yaml all of which still crashed, here is my current.
log: 
 -
  format: "plain"
  level: "info"
  output: "stderr"
p2p: 
  listen_address: "/ip4/192.168.1.116/tcp/3100" 
  public_address: "/ip4/<my.pub.ip.add>/tcp/3100"
  topics_of_interest: 
    blocks: "high"
    messages: "high"
  max_connections: 148
  trusted_peers:
    - address: "/ip4/52.9.132.248/tcp/3000"
      id: "671a9e7a5c739532668511bea823f0f5c5557c99b813456c"
    - address: "/ip4/52.8.15.52/tcp/3000"
      id: "18bf81a75e5b15a49b843a66f61602e14d4261fb5595b5f5"
    - address: "/ip4/13.114.196.228/tcp/3000"
      id: "7e1020c2e2107a849a8353876d047085f475c9bc646e42e9"
    - address: "/ip4/13.112.181.42/tcp/3000"
      id: "52762c49a84699d43c96fdfe6de18079fb2512077d6aa5bc"
    - address: "/ip4/3.125.75.156/tcp/3000"
      id: "22fb117f9f72f38b21bca5c0f069766c0d4327925d967791"
    - address: "/ip4/52.28.91.178/tcp/3000"
      id: "23b3ca09c644fe8098f64c24d75d9f79c8e058642e63a28c"
    - address: "/ip4/3.124.116.145/tcp/3000"
      id: "99cb10f53185fbef110472d45a36082905ee12df8a049b74"
rest: 
  listen: "127.0.0.1:3101"
storage: "./storage"
explorer:
 enabled: false
mempool:
  fragment_ttl: 2h
  log_ttl: 12h
  garbage_collection_interval: 2h
leadership:
  log_ttl: 2h
  garbage_collection_interval: 2h

**Comment by rickymac68** [comment]
This is the same issue as I had filed before https://github.com/input-output-hk/jormungandr/issues/953

**Comment by NicolasDP** [comment]
We have [code to handle that](https://github.com/input-output-hk/chain-libs/blob/f34839620c5824c5a4d4e80b6040f73eac3a4e69/network-grpc/src/server.rs#L119-L128). I have a macos too I will try to reproduce the settings.

## Question for you

- [ ] Are you using the released binaries we have produced or compiling yourself?
- [ ] can you check the following command: `shasum -a 1 $(which jormungandr)` (just to be sure).

## Question for me

- [ ] our build engine didn't have an updated submodule?
    - it seems they already do [`github clone --recursive` by default](https://docs.travis-ci.com/user/customizing-the-build/#git-submodules).
    - yet I will do a check too on our side
- [ ] reproducing the issue (see below)

### reproducing the issue

using `jormungandr` built by [our CI](https://github.com/input-output-hk/jormungandr/releases/tag/v0.8.2), the mac os version which sha1: `14e5dac172eac9b3d8168f33246afe8cfb34c689` (used command `shasum -a 1 jormungandr`).

using configuration file:

```yaml
p2p:
  topics_of_interest:
    messages: high
    blocks: high
  public_address: "/ip4/<somewhere>/tcp/<port>"
  listen_address: "/ip4/<somehow>/tcp/<port>"
  public_id: "some_id"
  trusted_peers:
    - address: "/ip4/52.9.132.248/tcp/3000"
      id: "671a9e7a5c739532668511bea823f0f5c5557c99b813456c"
    - address: "/ip4/52.8.15.52/tcp/3000"
      id: "18bf81a75e5b15a49b843a66f61602e14d4261fb5595b5f5"
    - address: "/ip4/13.114.196.228/tcp/3000"
      id: "7e1020c2e2107a849a8353876d047085f475c9bc646e42e9"
    - address: "/ip4/13.112.181.42/tcp/3000"
      id: "52762c49a84699d43c96fdfe6de18079fb2512077d6aa5bc"
    - address: "/ip4/3.125.75.156/tcp/3000"
      id: "22fb117f9f72f38b21bca5c0f069766c0d4327925d967791"
    - address: "/ip4/52.28.91.178/tcp/3000"
      id: "23b3ca09c644fe8098f64c24d75d9f79c8e058642e63a28c"
    - address: "/ip4/3.124.116.145/tcp/3000"
      id: "99cb10f53185fbef110472d45a36082905ee12df8a049b74"
rest:
  listen: "127.0.0.1:8080"
storage: /somewhere/in/my/directory/storage
```

starting my node with:

```
./jormungandr \
  --config config.yaml \
  --genesis-block-hash 8e4d2a343f3dcf9330ad9035b3e8d168e6728904262f2c434a4f8f934ec7b676
```
