### ISSUE TITLE
jcli rest v0 account get reports previous rewards when no rewards earned. Should report 0.

### ISSUE THREAD

**Issue by JSCSJSCS** [input-output-hk/jormungandr#1524]
**Describe the bug**
If, during a previous epoch when rewards were earned, at the start of the next epoch, if no rewards were earned, the results of ./jcli rest v0 account get "address" -h http://127.0.0.1:3101/api will again show the rewards earned during the last epoch that rewards were earned (even though the epoch number lists current epoch which is not the issue). Again, if during the subsequent epoch, no rewards were earned, the results of the above command nearly echos the previous epoch results when rewards were earned. It should report that zero rewards were earned, not just go back and report the LAST rewards earned.

**Mandatory Information**
Operating System: Windows 10 Home build 1903 64bit
Intel I7-9750H CPU @2.6GHz, 16GB RAM

1. jcli 0.8.5 (HEAD-3db06807, release, windows [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.5 (HEAD-3db06807, release, windows [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Run stake pool, win slots, make blocks, look at account get output
2. Have reduced delegates so no slots leader slots were won on next epoch
3. Run jcli rest v0 account get again and see that previous epochs rewards are listed even though 0 rewards were earned.

**Expected behavior**
A better, more accurate and less confusing result for the jcli account get would have been:
last_rewards:                        
  epoch: 25
  reward: 0
value: 157150339063

**Additional context**
Partial output of 3 epoch jcli account get and stake-pool get for comparison.
```
Start of Epoch 24 results of jcli account get for epoch 23 rewards
last_rewards:
  epoch: 24
  reward: 366347498
value: 156570902438

rewards:
  epoch: 24
  value_for_stakers: 5908922623
  value_taxed: 310995927
tax:
  fixed: 0
  ratio:
    denominator: 100
    numerator: 5
total_stake: 302240899980

Start of Epoch 25 results of jcli account get for epoch 24 rewards
last_rewards:
  epoch: 25
  reward: 579436625
value: 157150339063

rewards:
  epoch: 25
  value_for_stakers: 9343168247
  value_taxed: 491745697
tax:
  fixed: 0
  ratio:
    denominator: 100
    numerator: 5
total_stake: 2034211528123

Start of Epoch 26 results of jcli account get for epoch 25 rewards
Epoch 25 ***cardano-wallet stake showed 301,822,679,152 Lovelace - 0 slots
****Below is a repeat mostly of Epoch 24 results. Should show 0
last_rewards:                        
  epoch: 25
  reward: 579436625
value: 157150339063


rewards:
  epoch: 25
  value_for_stakers: 9343168247
  value_taxed: 491745697
tax:
  fixed: 0
  ratio:
    denominator: 100
    numerator: 5
total_stake: 2451949773528
```
