### ISSUE TITLE
Cannot sign the block: This leader 1 is not in the enclave

### ISSUE THREAD

**Issue by tstdin** [input-output-hk/jormungandr#1540]
**Describe the bug**
In the output of `jcli rest v0 leaders logs get` I noticed the following entry saying it couldn't sign the block.
```
- created_at_time: "2020-01-13T04:33:07.183929045+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-01-13T05:14:05.055529842+00:00"
  scheduled_at_date: "30.18014"
  scheduled_at_time: "2020-01-13T05:14:05+00:00"
  status:
    Rejected:
      reason: "Cannot sign the block: This leader 1 is not in the enclave"
```

But it seems this specific block has been accepted https://explorer.incentivized-testnet.iohkdev.io/block/b2edb19b0017bc5290fccbf067dd775a39c8a3dcba7ab38c677cde07186bb32e

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.8.5 (HEAD-3db0680, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. `jormungandr --full-version` output;
jormungandr 0.8.5 (master-b45d2355, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Run Jormungandr
2. Wait

**Expected behavior**
No signing errors.

**Additional context**
The logs with severity >= WARN do not contain anything about this incident.
