### ISSUE TITLE
data consistent between node and chain

### ISSUE THREAD

**Issue by fangio10** [input-output-hk/jormungandr#1571]
**Describe the bug**
node database has additional blocks compared to explorer/main chain

**Mandatory Information**
1. jcli 0.8.5
2. jormungandr 0.8.5

**To Reproduce**
1. run leader node
2. maintain sync during elected slot, mint slot locally
3. slot for some reason isn't propagated to main chain
4. minted block present in local db but not present on main chain

**Expected behavior**
for whatever reason the local block wasn't propagated to the main chain, once this happens the nodes local db is no longer a copy of the main chain (ie an additional block), shouldn't this additional block be discarded on the local node so that the local nodes database is consistent with the blockchain?

**Additional context**
main chain has slots 31806, 31824
local node has slots 31806, 31818, 31824

```
- created_at_time: "2020-01-15T11:09:05.594870867+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-01-15T12:54:13.031789465+00:00"
  scheduled_at_date: "32.31818"
  scheduled_at_time: "2020-01-15T12:54:13+00:00"
  status:
    Block:
      block: d2719603037c01162aca401d785128f8ef08a4fbcabcbb26b7cfc0d83c71a3ff
      chain_length: 100609
  wake_at_time: "2020-01-15T12:54:13.013225727+00:00"
```

jcli rest v0 block d2719603037c01162aca401d785128f8ef08a4fbcabcbb26b7cfc0d83c71a3ff get
```02b60002000000000000002000007c4a000189010e5751c026e543b2e8ab2eb06099daa1d1e5df47778f7787faab45cdf12fe3a8320de5a32e9ce670701e33d64741192c4bf1319b174c33a698aefc04e74d4e1a9bd9a60f409881b8bd0d487a43c0b10849ed76b206436eb1cbe343957ebbb5b3be57542dc7d13efe5aa46eed8c91679b7b7c54bad03958d02b58b9423b2f8647a6671607cbaf27fd6b06e92808b70b8fb1fc43e3853fe56e1655bf8bd10d5307e58dfe42023330ba64f8fb68918bef4ecc66de16def182ae13d2eec1d2cde800000000003dbfb8835714d1805fc6d5db2dc6aeebc12463dc26b7404105030ba820597af948d0f2842d044831017b45945a946eb4a51554aa3981c79919ecf8741d287a0b44d020a6f54d80811924658a75428016c1e7145f6f49da97dbb45b3a7c9f7c12527d1791939902470e05f260cdc7936ae425bd8b0e16e056bde8bd33611b44ac103bd4b6ebee6950da71023dc81e267fcff7a31208454aef6acb0fc6e3f9188d06d6d7d3832b2c1c3e49c5087d64e27f5a42a15c66fb652529d42692c2f5692ccf938ecc21863ec5d9c506c9fb459138f7d826ce6bc5c1f809b94035c3bd7f77352c67bb6fb5c36f37edd94ba2948b5f523027896a88a74ce0380a857dcffea08eefa273f77adc343e572ed88736883ecf3b67f2f0aeb6acd8e312c64bec736bfd55722d5a6768b942f7ebb9fce99a6d345f17a051a1130715fdc0849ea88d56487939e7be2f42e5b924865f545f58bba233028dad94921f15cb37a1b6d1de2f35c02a354849797874bc0e58b90cd89adb3fb1194e93ba046598bd3cf726eee3fb23c44ff47c760df7c6e95bfab80e83d09832f350cd7dd443eb71adbee675895d20eaa74bb55a828c53eceaeff5d0c069fdc131dc3a056c74d31400b247a40c5e5d65a5ccd654ca048913c09e0b2a304e6fe30b3aafc3e12b95412c53590df9```
