### ISSUE TITLE
ERRO Eek... Too late, we missed an event schedule, system time might be off?

### ISSUE THREAD

**Issue by adascanBovich** [input-output-hk/jormungandr#1580]
**Describe the bug**
My nodes keep missing blocks from time to time because of "ERRO Eek... Too late, we missed an event schedule, system time might be off?" error. System clock is in sync, ntp installed. Happens on different nodes, no pattern, one node can lose block for this error, then make 3 in a row just fine.

**Mandatory Information**
1. jcli 0.8.6 (HEAD-7686397, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]
2. jormungandr 0.8.6 (HEAD-7686397, release, linux [x86_64]) - [rustc 1.40.0 (73528e339 2019-12-16)]

**To Reproduce**
1. Start a pool.
2. Check logs every time you are missing your blocks.
3. Try no to cry.

**Expected behavior**
Blocks should be creating just fine with system clock synced.

**Additional context**
Couple of examples:

<img width="714" alt="Screenshot 2020-01-16 at 13 43 40" src="https://user-images.githubusercontent.com/58727428/72541306-f416d200-388a-11ea-90e5-23be4710a02d.png">

<img width="706" alt="Screenshot 2020-01-16 at 18 01 49" src="https://user-images.githubusercontent.com/58727428/72541322-faa54980-388a-11ea-8f67-0bd61d078fa3.png">

**Comment by Proxiweb** [comment]
I had this one two time with 0.8.6. I switched back to 0.8.5. Not happening again.

**Comment by mmahut** [comment]
Seeing this as well.

```
Jan 16 15:44:37.326 ERRO Eek... Too late, we missed an event schedule, system time might be off?, event_end: 2020-01-16T14:44:37+00:00, event_start: 2020-01-16T14:44:35+00:00, event_date: 33.35129, leader_id: 1, task: leadership
Jan 16 17:43:52.056 ERRO Eek... Too late, we missed an event schedule, system time might be off?, event_end: 2020-01-16T16:43:51+00:00, event_start: 2020-01-16T16:43:49+00:00, event_date: 33.38706, leader_id: 1, task: leadership
```

However, not all the time:

```
---
- created_at_time: "2020-01-16T07:20:28.087825432+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-01-16T15:58:29.011607694+00:00"
  scheduled_at_date: "33.37346"
  scheduled_at_time: "2020-01-16T15:58:29+00:00"
  status:
    Block:
      block: 5a60962d5592ff31bc9e89a3cedd167bbeab510ce0b9cc7cb749ec1248828c8d
      chain_length: 103869
  wake_at_time: "2020-01-16T15:58:29.001486315+00:00"
- created_at_time: "2020-01-16T07:20:28.087826193+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-01-16T16:41:43.009136451+00:00"
  scheduled_at_date: "33.38643"
  scheduled_at_time: "2020-01-16T16:41:43+00:00"
  status:
    Block:
      block: 27a03c579d2901787163c7e40c2966265ebf7007590766067c4deab1cc2bb0b8
      chain_length: 103962
  wake_at_time: "2020-01-16T16:41:43.005696007+00:00"
- created_at_time: "2020-01-16T07:20:28.087826973+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-01-16T16:43:52.057019303+00:00"
  scheduled_at_date: "33.38706"
  scheduled_at_time: "2020-01-16T16:43:49+00:00"
  status:
    Rejected:
      reason: Missed the deadline to compute the schedule
  wake_at_time: "2020-01-16T16:43:52.056439497+00:00"
```

NTP appears to be on spot according to monitoring.

**Comment by hodlonaut** [comment]
Can confirm this is happening here too - all nodes on the machine are up and seemingly in sync, in my case the leader ids were switched from node A to B about 7 seconds prior to the leader event but leader logs should have been identical... then when time arrived, the node without leader ids woke up the leadership event on time while the other one was late...

3 second delay doesn't seem to be a coincidence, feels like a bug somewhere

greg2@myserver2-4gb-hel1-1:~/cardano/jormungandr$ ./logs8502.sh | grep -C 6 "34.8703"
  scheduled_at_time: "2020-01-17T16:54:11+00:00"
  status: Pending
  wake_at_time: ~
- created_at_time: "2020-01-16T23:09:12.648007808+00:00"
  enclave_leader_id: 3
  finished_at_time: "2020-01-17T00:03:46.302390633+00:00"
  scheduled_at_date: "34.8703"
  scheduled_at_time: "2020-01-17T00:03:43+00:00"
  status:
    Rejected:
      reason: Missed the deadline to compute the schedule
  wake_at_time: "2020-01-17T00:03:46.302292649+00:00"



greg2@myserver2-4gb-hel1-1:~/cardano/jormungandr$ ./logs8504.sh | grep -C 6 "34.8703"
  scheduled_at_time: "2020-01-17T12:26:59+00:00"
  status: Pending
  wake_at_time: ~
- created_at_time: "2020-01-16T23:25:18.369987314+00:00"
  enclave_leader_id: 3
  finished_at_time: "2020-01-17T00:03:43.007313512+00:00"
  scheduled_at_date: "34.8703"
  scheduled_at_time: "2020-01-17T00:03:43+00:00"
  status:
    Rejected:
      reason: "Cannot sign the block: This leader 3 is not in the enclave"
  wake_at_time: "2020-01-17T00:03:43.001179318+00:00"

**Comment by PegasusPool** [comment]
Same issue here on 0.8.6.
Tried both chrony and NTP but doesn't seem to make any difference.

**Comment by NicolasDP** [comment]
Thanks everyone. I will be looking into this for the next release.

**Comment by hodlonaut** [comment]
@NicolasDP And here are example INFO level logs preceding the issue - showing that the node is busy doing other things instead of waking up for the very important event:

Jan 17 23:48:42.545 INFO connecting to peer, node_id: 1aef7c3bdd297f099577f527b1d9dd4c8cbabe717591ebf2, peer_addr: 138.68.109.144:3000, task: network
Jan 17 23:48:42.645 INFO connection to peer failed, reason: protocol handshake failed: unknown error, node_id: 63e779f013cd9bfe4838b5e4e7bd09f81525b3fe3cca76b0, peer_addr: 208.113.200.150:3000, task: network
Jan 17 23:48:42.664 INFO move node to quarantine, id: 63e779f013cd9bfe4838b5e4e7bd09f81525b3fe3cca76b0, sub_task: policy, task: poldercast
Jan 17 23:48:42.664 INFO connecting to peer, node_id: 46b7cc025dea756b1b5fd6891a3fd92d268076b592ede391, peer_addr: 52.214.209.130:3000, task: network
Jan 17 23:48:42.711 INFO failed to connect to peer, reason: Connection refused (os error 111), node_id: 46b7cc025dea756b1b5fd6891a3fd92d268076b592ede391, peer_addr: 52.214.209.130:3000, task: network
Jan 17 23:48:42.727 INFO move node to quarantine, id: 46b7cc025dea756b1b5fd6891a3fd92d268076b592ede391, sub_task: policy, task: poldercast
Jan 17 23:48:42.880 INFO connecting to peer, node_id: 2e209da744cc345bc31602a197269cb64221c0d22c172b6b, peer_addr: 95.179.219.33:8650, task: network
Jan 17 23:48:42.999 INFO connecting to peer, node_id: 4c829a23c738934b52acfe2a9c3958e3ee6a0156b42f8c28, peer_addr: 15.222.159.21:3000, task: network
Jan 17 23:48:43.255 INFO connecting to peer, node_id: 7cbf1bf5dfbfcd3b0e6c6b2a8a105d8c49644131a202e6ef, peer_addr: 79.114.244.247:3000, task: network
Jan 17 23:48:43.374 INFO accepted connection, peer_addr: 62.202.33.120:31132, local_addr: 0.0.0.0:4093, task: network

Jan 17 23:48:43.374 ERRO Eek... Too late, we missed an event schedule, system time might be off?, event_end: 2020-01-17T22:48:43+00:00, event_start: 2020-01-17T22:48:41+00:00, event_date: 35.6452, leader_id: 3, task: leadership

**Comment by Straightpool** [comment]
Just had the same error on my first and only slot assignment so far. Nod was on 0.8.6 with chrony installed and perfectly in sync:

- created_at_time: "2020-01-18T15:10:16.147301467+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-01-18T15:20:00.787124095+00:00"
  scheduled_at_date: "35.36190"
  scheduled_at_time: "2020-01-18T15:19:57+00:00"
  status:
    Rejected:
      reason: Missed the deadline to compute the schedule
  wake_at_time: "2020-01-18T15:20:00.787037638+00:00"

Logs shows
Jan 18 15:20:00 vps760672 start_leader.sh[44874]: Jan 18 15:20:00.788 ERRO Eek... Too late, we missed an event schedule, system time might be off?, event_end: 2020-01-18T15:19:59+

**Comment by BitcoinMicroPaymentNetwork** [comment]
I am also getting it . complete log below .

Rohits-MacBook-Pro:jormungandr-v0.8.5-x86_64-apple-darwin rohitchandan$ jcli rest v0 leaders logs get -h http://127.0.0.1:3100/api
---
- created_at_time: "2020-01-18T19:13:49.422786+00:00"
  enclave_leader_id: 1
  finished_at_time: ~
  scheduled_at_date: "36.37064"
  scheduled_at_time: "2020-01-19T15:49:05+00:00"
  status: Pending
  wake_at_time: ~
Rohits-MacBook-Pro:jormungandr-v0.8.5-x86_64-apple-darwin rohitchandan$ jcli rest v0 leaders logs get -h http://127.0.0.1:3100/api
---
- created_at_time: "2020-01-18T19:13:49.422786+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-01-19T15:49:07.483840+00:00"
  scheduled_at_date: "36.37064"
  scheduled_at_time: "2020-01-19T15:49:05+00:00"
  status:
    Rejected:
      reason: Missed the deadline to compute the schedule
  wake_at_time: "2020-01-19T15:49:07.482823+00:00"
Rohits-MacBook-Pro:jormungandr-v0.8.5-x86_64-apple-darwin rohitchandan$

**Comment by fedot-netot** [comment]
Got the same issue.

I am confused by the huge gap of 7 seconds between `scheduled_at_time` and `wake_at_time`. Node host time is in sync and `chrony` is running. Host with the node has quite enough resources: 4G RAM, SSD disk, and CPU utilization rarely exceeds 30%. At the moment of schedule the node had ~500 established network connnections with othes. Logging level of the node is configured as INFO. Jormungandr is the only service running on the host, except crony, systemd and some homemade monitoring tools.

```
---
- created_at_time: "2020-01-21T02:09:45.709170842+00:00"
  enclave_leader_id: 2
  finished_at_time: "2020-01-21T17:00:56.079760136+00:00"
  scheduled_at_date: "38.39216"
  scheduled_at_time: "2020-01-21T17:00:49+00:00"
  status:
    Rejected:
      reason: Missed the deadline to compute the schedule
  wake_at_time: "2020-01-21T17:00:56.079723536+00:00"
```
