### ISSUE TITLE
v0.8.10 panic  in Result::unwrap

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/jormungandr#1793]
**Describe the bug**

Jormungandr panic after running for almost an hour.

Feb 14 07:20:52.347 ERRO task process block announcement finished with error, error: Error(Msg("cannot process block announcement"), State { next_error: Some(Error(Msg("cannot check if the block is in the storage"), State { next_error: Some(BackendError(TimedOut)), backtrace: InternalBacktrace { backtrace: None } })), backtrace: InternalBacktrace { backtrace: None } }), task: block
Feb 14 07:20:52.744 ERRO task process block announcement timedout, task: block
Feb 14 07:20:52.744 ERRO task process block announcement timedout, task: block
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', src/libcore/result.rs:1188:5

**Mandatory Information**

1. `jcli --full-version` output;
jcli 0.8.10 (HEAD-ed9f7550, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]

2. `jormungandr --full-version` output;
jormungandr 0.8.10 (HEAD-ed9f7550, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]

**To Reproduce**

1. Run jormungandr v0.8.10 as a passive node.
2. Wait an hour.
3. Jormungandr stops and see panic in logs.

**Expected behavior**

Jormungandr should handle error and keep running.

**Additional context**

Ubuntu 18.04 on AWS c5n.large instance (5G mem, 2 vCPUs).
Server config:

```
---
leadership:
    garbage_collection_interval: 30m
    log_ttl: 24h
log:
- format: plain
  level: warn
  output: stderr
mempool:
    fragment_ttl: 30m
    garbage_collection_interval: 5m
    log_max_entries: 300000
    log_ttl: 1h
    pool_max_entries: 30000
rest:
  listen: "127.0.0.1:20001"
storage: /home/ubuntu/chains/jormungandr-itn_rewards_v1
p2p:
  gossip_interval: 2s
  listen_address: "/ip4/0.0.0.0/tcp/20002"
  max_bootstrap_attempts: 0
  max_connections: 2048
  max_unreachable_nodes_to_connect_per_event: 128
  public_address: "/ip4/107.23.61.45/tcp/20002"
  public_id: 7fc16a1df7f432686eca167f42a163734af7512100a78fd5
  topics_of_interest:
    blocks: normal
    messages: normal
  trusted_peers:
[... list of peers ...]
```
