### ISSUE TITLE
Jormungandr v0.8.10-2 panic in Option::unwrap, not staying in sync, REST timeout

### ISSUE THREAD

**Issue by shawnim** [input-output-hk/jormungandr#1812]
**Describe the bug**

Jormungandr v0.8.10-2 panic in Option::unwrap, not staying in sync, REST timeout.
Have to restart about every 20 to 60 minutes.
Note that some REST node stats requests succeed after a delay but some timeout.
This is in comparison to a similarly sized server which has been running v0.8.6 with the same configuration continuously and in sync for over 21 days.

**Mandatory Information**

1. `jcli --full-version` output;
jcli 0.8.10 (HEAD-ed9f7550, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]

2. `jormungandr --full-version` output;
jormungandr 0.8.10 (HEAD-ed9f7550, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]

**To Reproduce**

1. Run jormungandr v0.8.10-2 as a passive node.
2. Wait an hour.
3. Jormungandr is out of sync and needs to be restarted.

**Expected behavior**

Jormungandr v0.8.10 should stay in sync and respond to REST calls as well as or better than v0.8.6.

**Additional context**

Ubuntu 18.04 on AWS c5n.large instance (5G mem, 2 vCPUs).

I had set RUST_BACKTRACE=1 in my environment but I now realize that the server was getting restarted by a cron job that did not have that environment.  I will fix and see if I can get a full backtrace.

Node config

```
---
leadership:
    garbage_collection_interval: 30m
    log_ttl: 24h
log:
- format: plain
  level: warn
  output: stderr
mempool:
    fragment_ttl: 30m
    garbage_collection_interval: 5m
    log_max_entries: 300000
    log_ttl: 1h
    pool_max_entries: 30000
rest:
  listen: "127.0.0.1:20001"
storage: /home/ubuntu/chains/jormungandr-itn_rewards_v1
p2p:
  gossip_interval: 2s
  listen_address: "/ip4/0.0.0.0/tcp/20002"
  max_bootstrap_attempts: 0
  max_connections: 2048
  max_unreachable_nodes_to_connect_per_event: 128
  public_address: "/ip4/107.23.61.45/tcp/20002"
  public_id: 7fc16a1df7f432686eca167f42a163734af7512100a78fd5
  topics_of_interest:
    blocks: normal
    messages: normal
  trusted_peers:
[... list of peers ...]
```

Recent restart times (YYYYMMDDHHMMSS)

20200219140112
20200219142701
20200219145502
20200219154631
20200219162834
20200219171816
20200219175541
20200219184650
20200219193624
20200219201134

Status before recent restart

---
blockRecvCnt: 159
lastBlockContentSize: 564
lastBlockDate: "68.1371"
lastBlockFees: 1200000
lastBlockHash: 15340e60c10bf67b1e5702d649ec9dfa84e5e091d3fd765cd881ecf2ab7ee5d2
lastBlockHeight: "219381"
lastBlockSum: 65302472456
lastBlockTime: "2020-02-19T19:59:19+00:00"
lastBlockTx: 2
lastReceivedBlockTime: "2020-02-19T19:59:32+00:00"
nodeId: 7fc16a1df7f432686eca167f42a163734af7512100a78fd5
peerAvailableCnt: 9874
peerQuarantinedCnt: 45
peerTotalCnt: 10240
peerUnreachableCnt: 321
state: Running
txRecvCnt: 38
uptime: 1565
version: jormungandr 0.8.10-ed9f7550
server: passive2
failed to make a REST request
  |-> connection with node timed out
  |-> http://127.0.0.1:20001/api/v0/node/stats: timed out
hashFound: yes
blockSelfDelta: 0
blockSelfDiagnosis: stalled
blockExplorerDelta: 14
blockExplorerDiagnosis: serious lag
timeDelta: 13
timeDiagnosis: current
nodeCount: 477
date: Wed Feb 19 20:06:14 UTC 2020
timeToNextSlotLead: unknown

Log highlights

Feb 19 19:36:37.222 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Feb 19 19:39:36.946 WARN maximum allowable bootstrap attempts exceeded, continuing..., task: bootstrap
(many) Feb 19 19:39:39.633 WARN response canceled by the processing task, request: PushHeaders, sub_task: server, task: network
(many) Feb 19 19:56:29.812 ERRO task process block announcement timedout, task: block
(many) Feb 19 19:58:23.911 ERRO task process network blocks timedout, task: block
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
Feb 19 20:00:04.036 WARN request timed out or failed unexpectedly, error: Error(Elapsed), request: GetHeadersRange, task: client-query
Feb 19 20:00:21.883 WARN response canceled by the processing task, request: UploadBlocks, sub_task: server, task: network
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/macros/mod.rs:15:40
Feb 19 20:10:00.113 ERRO cannot process network headers, reason: Error(Elapsed), sub_task: chain_pull, task: block
Feb 19 20:10:00.113 ERRO process network headers finished with error, error: (), task: block
