### ISSUE TITLE
No connections after bootst

### ISSUE THREAD

**Issue by mark-stopka** [input-output-hk/jormungandr#1837]
**Describe the bug**
Jormungandr was unable to discover any connections after bootstrap and stayed without connections...

**Mandatory Information**
1. `jcli --full-version` output;
```
$ docker exec -i c1f336205a05 jcli --full-version
jcli 0.8.11 (HEAD-241e01e6, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]
```
2. `jormungandr --full-version` output;
```
$ docker exec -i c1f336205a05 jormungandr --full-version
jormungandr 0.8.11 (HEAD-241e01e6, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)]
```

3. `node_config.yaml`
```
---
log:
  - format: plain
    level: info
    output: stderr
http_fetch_block0_service:
  - https://bltn.2ndlayer.eu/bootstrap/
p2p:
  listen_address: "/ip4/0.0.0.0/tcp/3000"
  max_connections: 1024
  max_unreachable_nodes_to_connect_per_event: 10
  gossip_interval: 10s
  topics_of_interest:
    blocks: high
    messages: high
  policy:
    quarantine_duration: 3min
  trusted_peers:
    - address: "/ip4/13.56.0.226/tcp/3000"
      id: "7ddf203c86a012e8863ef19d96aabba23d2445c492d86267"
    - address: "/ip4/54.183.149.167/tcp/3000"
      id: "df02383863ae5e14fea5d51a092585da34e689a73f704613"
    - address: "/ip4/52.9.77.197/tcp/3000"
      id: "fcdf302895236d012635052725a0cdfc2e8ee394a1935b63"
    - address: "/ip4/18.177.78.96/tcp/3000"
      id: "fc89bff08ec4e054b4f03106f5312834abdf2fcb444610e9"
    - address: "/ip4/3.115.154.161/tcp/3000"
      id: "35bead7d45b3b8bda5e74aa12126d871069e7617b7f4fe62"
    - address: "/ip4/18.182.115.51/tcp/3000"
      id: "8529e334a39a5b6033b698be2040b1089d8f67e0102e2575"
    - address: "/ip4/18.184.35.137/tcp/3000"
      id: "06aa98b0ab6589f464d08911717115ef354161f0dc727858"
    - address: "/ip4/3.125.31.84/tcp/3000"
      id: "8f9ff09765684199b351d520defac463b1282a63d3cc99ca"
    - address: "/ip4/3.125.183.71/tcp/3000"
      id: "9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67"
storage: /srv/cardano/jormungandr/storage/
explorer:
  enabled: false
rest:
  listen: 127.0.0.1:3100
```

**To Reproduce**
Not sure. However node stats after a while:
```
---
blockRecvCnt: 0
lastBlockContentSize: 0
lastBlockDate: "69.40752"
lastBlockFees: 0
lastBlockHash: cc40e55bed142f0a4bb282f46e15eb9f41d2f8e98da57db11a259d0f9a4996c3
lastBlockHeight: "226183"
lastBlockSum: 0
lastBlockTime: "2020-02-21T17:52:01+00:00"
lastBlockTx: 0
lastReceivedBlockTime: ~
nodeId: bb0e321c4520aef415207fdf278ddda1da843c4f51e6279d
peerAvailableCnt: 0
peerQuarantinedCnt: 0
peerTotalCnt: 0
peerUnreachableCnt: 0
state: Running
txRecvCnt: 0
uptime: 1854
version: jormungandr 0.8.11-241e01e6
```

**Expected behavior**

**Additional context**
