### ISSUE TITLE
Node version v0.8.13 as leader gets stuck every 2-3 hours after restart 

### ISSUE THREAD

**Issue by StakerSpace** [input-output-hk/jormungandr#1887]
**Describe the bug**
My node doesn't run longer than 2-3 hours stable. I have tried tweaking my node-config to get an optimal result, I tried different configurations in order to solve this, but I don't think it's the node-config. 

**Mandatory Information**
1. `jcli --full-version` jcli 0.8.13 (HEAD-241b3a59, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)];
2. `jormungandr --full-version` jormungandr 0.8.13 (HEAD-241b3a59, release, linux [x86_64]) - [rustc 1.41.0 (5e1a79984 2020-01-27)];

**To Reproduce**
1. When the process of `jormungandr` has stopped, I'll run it with `start_leader` with the following configuration. 
```
log:
- output: stderr
  format: plain
  level: info
http_fetch_block0_service:
  - "https://github.com/input-output-hk/jormungandr-block0/raw/master/data/"
skip_bootstrap: false
bootstrap_from_trusted_peers: false
p2p:
  listen_address: "/ip4/0.0.0.0/tcp/17900"
  public_address: "/ip4/x.x.x.x/tcp/17900"
  topics_of_interest:
    blocks: high
    messages: high
  max_connections: 600
  max_bootstrap_attempts: 3
  max_unreachable_nodes_to_connect_per_event: 18
  gossip_interval: 5s
  policy:
    quarantine_duration: 10m
  trusted_peers:
    - address: "/ip4/3.231.168.222/tcp/3000"
      id: ff2aaaac6cab77d3fb72bf3cb9079246eca323c60b2fd68a
    - address: "/ip4/13.56.0.226/tcp/3000"
      id: 7ddf203c86a012e8863ef19d96aabba23d2445c492d86267
    - address: "/ip4/52.28.91.178/tcp/3000"
      id: 23b3ca09c644fe8098f64c24d75d9f79c8e058642e63a28c
    - address: "/ip4/3.125.75.156/tcp/3000"
      id: 22fb117f9f72f38b21bca5c0f069766c0d4327925d967791
    - address: "/ip4/13.112.181.42/tcp/3000"
      id: 52762c49a84699d43c96fdfe6de18079fb2512077d6aa5bc
    - address: "/ip4/13.114.196.228/tcp/3000"
      id: 7e1020c2e2107a849a8353876d047085f475c9bc646e42e9
    - address: "/ip4/52.8.15.52/tcp/3000"
      id: 18bf81a75e5b15a49b843a66f61602e14d4261fb5595b5f5
    - address: "/ip4/52.9.132.248/tcp/3000"
      id: 671a9e7a5c739532668511bea823f0f5c5557c99b813456c
    - address: "/ip4/3.125.183.71/tcp/3000"
      id: 9d15a9e2f1336c7acda8ced34e929f697dc24ea0910c3e67
    - address: "/ip4/18.184.35.137/tcp/3000"
      id: 06aa98b0ab6589f464d08911717115ef354161f0dc727858
    - address: "/ip4/18.182.115.51/tcp/3000"
      id: 8529e334a39a5b6033b698be2040b1089d8f67e0102e2575
    - address: "/ip4/3.115.154.161/tcp/3000"
      id: 35bead7d45b3b8bda5e74aa12126d871069e7617b7f4fe62
    - address: "/ip4/18.177.78.96/tcp/3000"
      id: fc89bff08ec4e054b4f03106f5312834abdf2fcb444610e9
    - address: "/ip4/52.9.77.197/tcp/3000"
      id: fcdf302895236d012635052725a0cdfc2e8ee394a1935b63
    - address: "/ip4/54.183.149.167/tcp/3000"
      id: df02383863ae5e14fea5d51a092585da34e689a73f704613
    - address: "/ip4/3.124.116.145/tcp/3000"
      id: 99cb10f53185fbef110472d45a36082905ee12df8a049b74
rest:
  listen: "127.0.0.1:3100"
storage: /home/ada/storage
explorer:
  enabled: false
mempool:
    pool_max_entries: 10000
    log_max_entries: 100000
leadership:
    logs_capacity: 4096
```
2. The node runs for some time and get's stuck very quickly and shoots up the amount of max_connections, that is usally a good indication that it's not registering any blocks. 
3. In the logs I see the following stuck-notifier messages:
```
Mar 05 16:02:43.091 WARN blockchain is not moving up, system-date=82.37473, the last tip c19b40e7-000426db-82.24939 was 25068 seconds ago, task: stuck_notifier
Mar 05 16:03:43.093 WARN blockchain is not moving up, system-date=82.37503, the last tip c19b40e7-000426db-82.24939 was 25128 seconds ago, task: stuck_notifier
Mar 05 16:04:43.093 WARN blockchain is not moving up, system-date=82.37533, the last tip c19b40e7-000426db-82.24939 was 25188 seconds ago, task: stuck_notifier
Mar 05 16:05:43.091 WARN blockchain is not moving up, system-date=82.37563, the last tip c19b40e7-000426db-82.24939 was 25248 seconds ago, task: stuck_notifier
Mar 05 16:06:43.092 WARN blockchain is not moving up, system-date=82.37593, the last tip c19b40e7-000426db-82.24939 was 25308 seconds ago, task: stuck_notifier
Mar 05 16:07:43.092 WARN blockchain is not moving up, system-date=82.37623, the last tip c19b40e7-000426db-82.24939 was 25368 seconds ago, task: stuck_notifier
Mar 05 16:08:43.093 WARN blockchain is not moving up, system-date=82.37653, the last tip c19b40e7-000426db-82.24939 was 25428 seconds ago, task: stuck_notifier
```
4. With a restart-script that checks if the node is stuck, that process also get clogged as sometimes it stops at bootstrapping process. 
5. As a result: 
```
Has this node been scheduled to be leader?
---
- created_at_time: "2020-03-05T07:33:47.290214282+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-03-05T12:50:41.000850225+00:00"
  scheduled_at_date: "82.31711"
  scheduled_at_time: "2020-03-05T12:50:39+00:00"
  status:
    Rejected:
      reason: Failed to compute the schedule within time boundaries
  wake_at_time: "2020-03-05T12:50:39.001462736+00:00"
```

**Expected behavior**
A stable node as a leader, running on 4cpu, 16gb machine with ubuntu server and doesn't do anything else.

**Comment by cardanoinvest** [comment]
Yeah similar, everything after v0.8.9 is getting stuck with no error.

**Comment by bergr01** [comment]
Sometimes happens on latest master (as of 10 March, 2020) as well. Hanging is characterized by the timing out of the 'jcli rest v0 network stats get' command:

jcli rest v0 network stats get | wc
failed to make a REST request
  |-> connection with node timed out
  |-> http://127.0.0.1:8504/api/v0/network/stats: timed out

netstat data for the hung node:

  1 CLOSE_WAIT
    471 ESTABLISHED
      2 LISTEN

no ERRO level messages in the log, the only WARN is the blockchain not moving - the only resolution so far seems to be a restart.

**Comment by ilhanu** [comment]
Same with the latest `v0.8.14`.

The node was up since 16:30 UTC, and started getting stuck at `89.40127` 

Mar 12 19:02:58.261 WARN blockchain is not moving up, system-date=89.42880, the last tip a7caa4b7-00048ca2-89.40127 was 5507 seconds ago, task: stuck_notifier
Mar 12 19:03:58.262 WARN blockchain is not moving up, system-date=89.42910, the last tip a7caa4b7-00048ca2-89.40127 was 5567 seconds ago, task: stuck_notifier
Mar 12 19:04:58.262 WARN blockchain is not moving up, system-date=89.42940, the last tip a7caa4b7-00048ca2-89.40127 was 5627 seconds ago, task: stuck_notifier
Mar 12 19:05:58.261 WARN blockchain is not moving up, system-date=89.42970, the last tip a7caa4b7-00048ca2-89.40127 was 5687 seconds ago, task: stuck_notifier
Mar 12 19:06:58.262 WARN blockchain is not moving up, system-date=89.43000, the last tip a7caa4b7-00048ca2-89.40127 was 5747 seconds ago, task: stuck_notifier
Mar 12 19:07:58.262 WARN blockchain is not moving up, system-date=89.43030, the last tip a7caa4b7-00048ca2-89.40127 was 5807 seconds ago, task: stuck_notifier
Mar 12 19:08:58.261 WARN blockchain is not moving up, system-date=89.43060, the last tip a7caa4b7-00048ca2-89.40127 was 5867 seconds ago, task: stuck_notifier
Mar 12 19:09:58.262 WARN blockchain is not moving up, system-date=89.43090, the last tip a7caa4b7-00048ca2-89.40127 was 5927 seconds ago, task: stuck_notifier
Mar 12 19:10:58.261 WARN blockchain is not moving up, system-date=89.43120, the last tip a7caa4b7-00048ca2-89.40127 was 5987 seconds ago, task: stuck_notifier
Mar 12 19:11:58.262 WARN blockchain is not moving up, system-date=89.43150, the last tip a7caa4b7-00048ca2-89.40127 was 6047 seconds ago, task: stuck_notifier
Mar 12 19:12:58.261 WARN blockchain is not moving up, system-date=89.43180, the last tip a7caa4b7-00048ca2-89.40127 was 6107 seconds ago, task: stuck_notifier

**Comment by bergr01** [comment]
Happening on 0.8.14 too - last time it happened the jormungandr process memory usage was at a whopping 3 GB RAM on a Linux box, and log file was filled with frequently repeating:

Mar 13 06:05:47.390 INFO create new branch with tip d3303226-000492c5-90.16469 | current-tip ba9806aa-00049307-90.17331, task: block
Mar 13 06:05:47.390 INFO create new branch with tip d4121349-000492c8-90.16482 | current-tip ba9806aa-00049307-90.17331, task: block
Mar 13 06:05:47.391 INFO create new branch with tip 26d198b0-000492ca-90.16515 | current-tip ba9806aa-00049307-90.17331, task: block
Mar 13 06:05:47.391 INFO create new branch with tip c693918a-000492cc-90.16541 | current-tip ba9806aa-00049307-90.17331, task: block
Mar 13 06:05:47.391 INFO create new branch with tip d8f8d24a-000492ce-90.16589 | current-tip ba9806aa-00049307-90.17331, task: block

**Comment by StakerSpace** [comment]
Still on version `v0.8.14`, Had one block planned this morning. The chain stopped moving first at `
e16b61bf-0004ad4f-92.14177` after that `31563e60-0004ad50-92.16623` which was the slot that was planned, didn't get into the ledger and that is exactly from where it didn't move further.

**The leader_logs:**
```
---
- created_at_time: "2020-03-14T22:07:36.161218829+00:00"
  enclave_leader_id: 1
  finished_at_time: "2020-03-15T04:27:43.006138376+00:00"
  scheduled_at_date: "92.16623"
  scheduled_at_time: "2020-03-15T04:27:43+00:00"
  status:
    Block:
      block: 31563e60e57414c7c443979af2bc8782b90ff048a686fc505a1b017d5cd50be0
      chain_length: 306512
      parent: e16b61bf485a68575567f3e596d7686a588c654efa2682adb3a016804e69cdc2
  wake_at_time: "2020-03-15T04:27:43.001058026+00:00"
```

**A long list of stuck notifiers:**
```
Mar 15 07:22:28.539 WARN blockchain is not moving up, system-date=92.21865, the last tip 31563e60-0004ad50-92.16623 was 10485 seconds ago, task: stuck_notifier
Mar 15 07:23:28.541 WARN blockchain is not moving up, system-date=92.21895, the last tip 31563e60-0004ad50-92.16623 was 10545 seconds ago, task: stuck_notifier
Mar 15 07:24:28.542 WARN blockchain is not moving up, system-date=92.21925, the last tip 31563e60-0004ad50-92.16623 was 10605 seconds ago, task: stuck_notifier
```
