### ISSUE TITLE
Stake distribution rest api does not update after reward distribution

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#1949]
**Describe the bug**
Stake distribution for current is still equal to stake distribution from previous epoch even if reward distribution was made.
0. I have a blockchain with:
- 2 unassigned accounts with  1_000_000_000 ADA each
- 1 pool owner with owner delegation certificate having 1_000_000_000 ADA
- 1 pool with id: `ca374845d196f0e5035cabb2340040a65ee1ccf9df1f68d2d882843891d16fca`
- transaction fee: (constant: 1, coeff: 1, cert: 1 )

1. First query for stake distribution:

```
Sending GET request: 'http://127.0.0.1:7034/api/v0/stake'
Response: {"epoch":0,"stake":{"dangling":0,"pools":[["ca374845d196f0e5035cabb2340040a65ee1ccf9df1f68d2d882843891d16fca",1000000000]],"unassigned":2000000000}}
```

2. Made transaction from unassigned account to delegated account (pool owner) for 1000 ada

```
- fragment_id: 54caae4dacff232f36771fc975de0991e9fabbbe1cb79542af5267c8bb22ce71
  last_updated_at: "2020-03-20T16:15:30.035796700+00:00"
  received_at: "2020-03-20T16:15:28.545749500+00:00"
  received_from: Rest
  status:
    InABlock:
      block: 3b63df0e985b938605248692097612bfb29deff9c4f35d6b103ef675982e7c10
      date: "0.5"
```

3. Waited some time to epoch end
4. Checked reward collected for epoch 0:

```
Sending GET request: 'http://127.0.0.1:7034/api/v0/rewards/epoch/1'
Response: {"epoch":1,"drawn":100000,"fees":3,"treasury":111,"stake_pools":{"ca374845d196f0e5035cabb2340040a65ee1ccf9df1f68d2d882843891d16fca":[10079,89813]},"accounts":{"ed25519_pk1rwxu32c4v7kcxqtg6tauphxavu5k3lanxtzcn02f8llkk8mwm9vs0wlld6":99892}}
```

5. Checked reward account for stake pool (it's owner account):

```
Running command: "C:\\Work\\iohk\\jormungandr\\target\\debug\\jcli.exe" "rest" "v0" "account" "get" "ca1s5dcmj9tz4n6mqcpdrf0hsxum4njj68lkvevtzdafyll76cldmv4jxqdqwp" "-h" "http://127.0.0.1:7034/api"
Output: ---
counter: 0
delegation:
  pools:
    - - ca374845d196f0e5035cabb2340040a65ee1ccf9df1f68d2d882843891d16fca
      - 1
last_rewards:
  epoch: 2 // looks like query took longer time than my epoch (60 s.)  so it returned for epoch 2
  reward: 99882
value: 1000200774
```

6. Checked  distribution

```
Sending GET request: 'http://127.0.0.1:7034/api/v0/stake/2'
Response: {"epoch":2,"stake":{"dangling":0,"pools":[["ca374845d196f0e5035cabb2340040a65ee1ccf9df1f68d2d882843891d16fca",1000001000]],"unassigned":1999998997}}
```

Distribution does not contains rewards transferred to owner account.
I've developed similar test case but in chain-libs and it's working as expected: 
https://github.com/input-output-hk/chain-libs/pull/306

**To Reproduce**
1. checkout branch https://github.com/input-output-hk/jormungandr/pull/1948
2. Run tests: `cargo test stake_distribution -- --nocapture`

**Expected behavior**
Stake distribution for pools should be equal to: `1000100892`

**Additional context**
