### ISSUE TITLE
REST Api 404 Error

### ISSUE THREAD

**Issue by robkorn** [input-output-hk/jormungandr#208]
**Describe the bug**
Attempting to use jormungandr_cli to get node stats via REST causes a 404 error with the configured ip/port. Also tried getting utxo but same problem.

Error:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` 
value: Error { kind: ClientError(404), 
url: Some("http://127.0.0.1:8443/v0/node/stats") }', src/libcore/result.rs:997:5

```

**To Reproduce**
`jormungandr_cli rest v0 node stats get --host http://127.0.0.1:8443`

**Expected behavior**
Response with node stats.

**Additional context**
Jormungandr node config used:
```
storage: "/tmp/storage"
logger:
  verbosity: 1
  format: json
rest:
  listen: "127.0.0.1:8443"
  prefix: "api"
peer_2_peer:
  trusted_peers: []
  public_access: "/ip4/127.0.0.1/tcp/8080"
  topics_of_interests:
    transactions: low
    blocks: normal
```
