### ISSUE TITLE
PoolUpdate fragment is lost in fragment pool

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#2272]
**Describe the bug**
If a pool update fragment is sent to the node it couldn't be find in fragment pool.
I've send all fragment types to the node and the issue is only with pool update fragment.

Sending:
```
Running command: "C:\\Work\\iohk\\jormungandr\\target\\debug\\jcli.exe" "rest" "v0" "message" "post" "-f" "C:\\Users\\Dariusz\\AppData\\Local\\Temp\\3422cf536d4e47558d502247e853920c\\transaction.hash" "-h" "http://127.0.0.1:8230/api"
Output: 0f98a69aaec55e79ae3e9c35116bd057291f64e0f3e7bc56639813cccbd35bb4
```  

Fragment Pool:

```
Running command "C:\\Work\\iohk\\jormungandr\\target\\debug\\jcli.exe" "rest" "v0" "message" "logs" "--host" "http://127.0.0.1:8230/api" in loop
Standard Output: ---
- fragment_id: 6c24f4ad51f686131bdffcfd624cb8a1fee402b2a27e7597e2f5a64a92bfe5f8
  last_updated_at: "2020-05-25T10:49:25.022837+00:00"
  received_at: "2020-05-25T10:49:24.642842600+00:00"
  received_from: Rest
  status:
    InABlock:
      block: 9f6e52b2a5bb2a6aedaf6147b14a63a090c9c9457364b6e7dd254b9f74d5093c
      date: "0.13"
- fragment_id: 4971596dd3be27094f5d07a1bc74e51f76484f69e1c197aa745f42c3d30c40d3
  last_updated_at: "2020-05-25T10:49:24.011862+00:00"
  received_at: "2020-05-25T10:49:23.023480900+00:00"
  received_from: Rest
  status:
    InABlock:
      block: c176c7a02794d99fc2b76885718f85830e9c84824f99d06e0af2a99ba4491352
      date: "0.12"
- fragment_id: 41c29cd21f23589184e1ff10af3051fdf835858f9c47041c073552daad3db6e5
  last_updated_at: "2020-05-25T10:49:22.012709100+00:00"
  received_at: "2020-05-25T10:49:21.370555500+00:00"
  received_from: Rest
  status:
    InABlock:
      block: 01c863210344dd5ae18220a4a66610e64958d1470cb23b0cab6f83764d8184d8
      date: "0.10"
- fragment_id: 77206035b545fade6e9524f7e513b16dfb3040f70e77dd2e3cd37c2c791e3d63
  last_updated_at: "2020-05-25T10:49:19.017038700+00:00"
  received_at: "2020-05-25T10:49:18.430755900+00:00"
  received_from: Rest
  status:
    InABlock:
      block: a0a3398ff8d5c9d06b52c1fb27b268e8c382f24d88cf643a90b204146b27e983
      date: "0.7"
- fragment_id: 7df2c3871b19b9312c3754705f11f1513610c3c97a98cff6d5cdeb7e4a5c5d20
  last_updated_at: "2020-05-25T10:49:17.011609500+00:00"
  received_at: "2020-05-25T10:49:16.906991600+00:00"
  received_from: Rest
  status:
    InABlock:
      block: 40124f15bd0429dd5f8e61c13b7717a0c8b6375e87443921729097dd98be41d3
      date: "0.5" 
```

**Mandatory Information**
1. `jcli --full-version` output: newest master
2. `jormungandr --full-version` : newest master

**To Reproduce**
1. Start node
2. Send pool registration fragment
3. Wait for next epoch
4. Send pool update fragment

**Expected behavior**
Fragment with pool update should be visible in fragment pool and at least as pending on rejected

**Additional context**
There is an automation tests which reproduces issue:
``` 
cd testing/jormungandr-integration-tests
cargo test test_all_fragments
```
