### ISSUE TITLE
factor out `toolchain` from this CI table and add the few outliers with `include`:

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#2310]
It might be more maintainable if we factor out `toolchain` from this table and add the few outliers with `include`:

```yaml
      matrix:
        config:
          # Linux
          - {os: ubuntu-latest, target: x86_64-unknown-linux-gnu, target_cpu: generic, cross: false}
          - {os: ubuntu-latest, target: x86_64-unknown-linux-gnu, target_cpu: broadwell, cross: false}
          # ...
        toolchain: stable
        include:
          # Windows
          - config: {os: windows-latest, target: x86_64-pc-windows-gnu, target_cpu: generic, cross: false}
            toolchain: stable-x86_64-pc-windows-gnu
          - config: {os: windows-latest, target: x86_64-pc-windows-msvc, target_cpu: generic, cross: false}
            toolchain: stable-x86_64-pc-windows-msvc
          # ...
```

Then, replace every occurrence of `${{ matrix.config.toolchain }}` with `${{ matrix.toolchain }}`.

_Originally posted by @mzabaluev in https://github.com/input-output-hk/jormungandr/pull/2306_
