### ISSUE TITLE
Correct transaction is rejected

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#237]
**Describe the bug**
transaction is rejected from node with error message 

```
qquququq b"\0\x96\x02\x01\x01\0\0\0\0\0\0\0\0d\xf7\xf1\xb6\r`3\xbfr@\x9f_\xca\x14\xfe\xa2\x1fez\x0c\xee\x19r\x91F5\x1ai\x8d+j\x85>\x83)\x91\xaaZ`YpBO!\x15S\xafm\x19\x9c'\xe3\\W\x19\xd2A^\xe4\x81{h\xbei-\xac\0\0\0\0\0\0\0F\x01\xe0\x9f_\xee\x1ai\xe4&\x9b\x99pH\xa5\x19\x18W\x92\xe6\x82\x19Q\xb0\xe0\xe9\x18G)\xe5@3\xbcQ\xbdf1\xd5\xdf\x8a\xab\x9b5\xbaP(\xfc\xf2\xe7\x8b\xa8#5\x83\x01v\x10\xd9\xfb\xb5\x1d\xb5\t\x17\xd1f"
Apr 02 11:23:18.043 WARN Received transactions where some are invalid, UtxoInvalidSignature(UtxoPointer { transaction_id: Hash(Blake2b256(0xf7f1b60d6033bf72409f5fca14fea21f657a0cee19729146351a698d2b6a853e)), output_index: 0, value: Value(100) }, Output { address: Address(Test, Single(3b99a2175a6297ef1100c1ed63dde2e4121b3c226d32de837b06500f36d65e4d)), value: Value(100) }, Utxo(e09f5fee1a69e4269b997048a519185792e6821951b0e0e9184729e54033bc51bd6631d5df8aab9b35ba5028fcf2e78ba8233583017610d9fbb51db50917d166)), task: transaction
```

and command:

> jcli rest v0 node stats get -h http://localhost:8081

has an output:

> blockRecvCnt: 0
> txRecvCnt: 0
> uptime: 2557

**Setup**

1) genesis.yaml:

```
blockchain_configuration:
  - [ block0-date, 1550822014 ]
  - [ discrimination, test ]
initial_setting:
  allow_account_creation: true
  slot_duration: 15
  epoch-stability-depth: 2600
  linear_fees:
    constant: 0
    coefficient: 0
    certificate: 0
  block_version: 1
  bft_leaders:
    - ed25519extended_public1k3wjgdcdcn23k6dwr0cyh88ad7a4ayenyxaherfazwy363pyy8wqppn7j3
    - ed25519extended_public13talprd9grgaqzs42mkm0x2xek5wf9mdf0eefdy8a6dk5grka2gstrp3en
initial_utxos:
  - address: ta1svy0mwwm7mdwcuj308aapjw6ra4c3e6cygd0f333nvtjzxg8ahdvxlswdf0
    value: 10000
```

a) address:
`ta1svaengshtf3f0mc3qrq76c7autjpyxeuyfkn9h5r0vr9qrek6e0y6zpe8ls`
is generated from private key:
 `ed25519extended_secret1uz04lms6d8jzdxuewpy22xgc27fwdqse2xcwp6gcgu572spnh3gm6e336h0c42umxka9q28u7tnch2prxkpszassm8am28d4pytazesx0n0fk`

b) address:

`ta1sv5er2j6vpvhqsj0yy248tmdrxwz0c6u2uvays27ujqhk697dyk6csdzwvm`

is generated from private key:

`ed25519extended_secret1zrxjspxan0uag0pdel67t8fqg90e29ud8cwxr5xcjv5pcjp02azuhkmx38u795zx3nlqtrsyrsekly9ct8nzad2hl57nanhy50ef4hgmdw538`

c) node.config

```
storage: "/tmp/storage"
logger:
  verbosity: 1
  format: json
rest:
  listen: "127.0.0.1:8443"
  prefix: "api"
peer_2_peer:
  trusted_peers: []
  public_access: "/ip4/127.0.0.1/tcp/8080"
  topics_of_interests:
    transactions: low
    blocks: normal
```

**To Reproduce**
1.  Checkout newest master 
2.  Generate block based on **genesis.yaml** file provided in setup section
3.  Start node with **node.config** file provided in setup section
`jormungandr.exe --genesis-block test\block-0.bin --config test\node.config --without-leadership`
4. build transaction:
`cli transaction build --input f7f1b60d6033bf72409f5fca14fea21f657a0cee19729146351a698d2b6a853e:1:100 --output ta1svaengshtf3f0mc3qrq76c7autjpyxeuyfkn9h5r0vr9qrek6e0y6zpe8ls:10 -s utxo1_address.secret`

while 

`f7f1b60d6033bf72409f5fca14fea21f657a0cee19729146351a698d2b6a853e` - initial transaction id

> cat utxo1_address.secret

`ed25519extended_secret1uz04lms6d8jzdxuewpy22xgc27fwdqse2xcwp6gcgu572spnh3gm6e336h0c42umxka9q28u7tnch2prxkpszassm8am28d4pytazesx0n0fk`

5. Post transaction with hash generated int step 4

**Expected behavior**
Transaction is accepted and command:

> cli rest v0 node stats get -h http://localhost:8081

Will give output like: 

```
blockRecvCnt: 0
txRecvCnt: 1
uptime: 2557
```
