### ISSUE TITLE
[JCLI][Transaction] Misleading error while building transaction when no spending key provided

### ISSUE THREAD

**Issue by dkijania** [input-output-hk/jormungandr#239]
**Describe the bug**
Assertion error instead of real error message is produced when no spending key is provided:

>  jcli transaction build --input f7f1b60d6033bf72409f5fca14fea21f657a0cee19729146351a698d2b6a853e:0:100 --output ta1sv5er2j6vpvhqsj0yy248tmdrxwz0c6u2uvays27ujqhk697dyk6csdzwvm:70

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `1`,
 right: `0`', cardano-deps\chain-impl-mockchain\src\transaction\mod.rs:28:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**To Reproduce**
1.  start node with genesis.yaml:
```
blockchain_configuration:
  - [ block0-date, 1554185140 ]
  - [ discrimination, test ]
initial_setting:
  allow_account_creation: true
  slot_duration: 15
  epoch_stability_depth: 2600
  linear_fees:
    constant: 0
    coefficient: 0
    certificate: 0
  block_version: 1
  bft_leaders:
    -  ed25519extended_public1nhnr6nfff3uhuky94evw9ejfxx9h5yhk6zk97kd5mssezlhlpryqy5xljp
    -  ed25519extended_public1gl7rvurvvsllkmp4xmt250s6jl85e0fprw3mk4e7fwuv5kmu7vtsftgku8
initial_utxos:
  - address: ta1svaengshtf3f0mc3qrq76c7autjpyxeuyfkn9h5r0vr9qrek6e0y6zpe8ls
    value: 100
  - address: ta1sv5er2j6vpvhqsj0yy248tmdrxwz0c6u2uvays27ujqhk697dyk6csdzwvm
    value: 100
```

2. build transaction:

> jcli transaction build --input f7f1b60d6033bf72409f5fca14fea21f657a0cee19729146351a698d2b6a853e:0:100 --output ta1sv5er2j6vpvhqsj0yy248tmdrxwz0c6u2uvays27ujqhk697dyk6csdzwvm:70

**Expected behavior**
A clear message that spending key argument is required or similar one.

**Additional context**
private key that can be used as an argument for **spending key** option: 

`ed25519extended_secret1uz04lms6d8jzdxuewpy22xgc27fwdqse2xcwp6gcgu572spnh3gm6e336h0c42umxka9q28u7tnch2prxkpszassm8am28d4pytazesx0n0fk`
