### ISSUE TITLE
Block0 fails as invalid in jormungandr: check error before writing the block0 to the output in the jcli

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#321]
Even though we can create a block0 without genesis praos parameter this is not reflected in the ledger.

For example, the following is valid genesis file but when loaded by the node it fails because of the missing parameter f (the `ConsensusGenesisPraosActiveSlotsCoeff`). Or this is a BFT blockchain not a genesis praos blockchain.

```yaml
blockchain_configuration:
  block0_date: 1556793742
  discrimination: test
  block0_consensus: bft
  slots_per_epoch: 5
  slot_duration: 15
  epoch_stability_depth: 10
  consensus_leader_ids:
    - ed25519e_pk185yr0q32tqkva59k083wx2uawxxpptc2pjt43pjez7ufjhlxdnks6avw8a
    - ed25519e_pk1hj8k4jyhsrva7ndynak25jagf3qcj4usnp54gnzvrejnwrufxpgqytzy6u

initial_setting:
  allow_account_creation: true
  linear_fee:
    constant: 2
    coefficient: 1
    certificate: 4

initial_funds:
  - address: ta1svy0mwwm7mdwcuj308aapjw6ra4c3e6cygd0f333nvtjzxg8ahdvxlswdf0
    value: 10000
```
