### ISSUE TITLE
default node-config.yaml can't parse

### ISSUE THREAD

**Issue by andrewarrow** [input-output-hk/jormungandr#3235]
Hello I've been trying to follow:

https://github.com/Chris-Graffagnino/Jormungandr-for-Newbs/blob/master/docs/jormungandr_node_setup_guide.md

or

https://github.com/Kevmate/Jormungandr-for-Newbs/blob/master/docs/jormungandr_node_setup_guide.md

but I can never get this yaml file:

```
log:
- output: stderr
  format: plain
  level: info
p2p:
  topics_of_interest:
    blocks: high
    messages: high
  listen_address: "/ip4/0.0.0.0/tcp/3000"
  public_address: "/ip4/161.35.232.233/tcp/3000"
  public_id: 1dec8c7f307d04fa0e3753b0d560857a20a3afc6a3e48cba
  max_connections: 1024
  gossip_interval: 10s
  trusted_peers:
    - address: "/ip4/13.56.0.226/tcp/3000"
      id: 7ddf203c86a012e8863ef19d96aabba23d2445c492d86267
    - address: "/ip4/54.183.149.167/tcp/3000"
```

to parse right.

errors like:

|-> Error while parsing the node configuration file: log[0]: invalid type: map, expected a string at line 2 column 9
 |-> log[0]: invalid type: map, expected a string at line 2 column 9

but something seems wrong since I didn't make any changes yet. I'm just trying to start up my Jormungandr node for the very first time. But there doesn't seem to be any example node-config.yaml that just works out of the box?
