### ISSUE TITLE
More structured genesis YAML for consensus parameters

### ISSUE THREAD

**Issue by mzabaluev** [input-output-hk/jormungandr#324]
The current YAML format for genesis has long snake-cased field names defining consensus parameters, prefixed with the type of the consensus algorithm (or not, in case of `consensus_leader_ids` which only applies to BFT).

It would be better to use the structural nature of YAML and group the parameters under shorter names:

```yaml
consensus:
  bft:
    leader_ids:
      - ed25519e_pk1hj8k4jyhsrva7ndynak25jagf3qcj4usnp54gnzvrejnwrufxpgqytzy6u
  genesis_praos:
    param_d: 0.22  # Wotsit, could have a better name too?
    active_slot_coeff: 0.22
```
