### ISSUE TITLE
Error when verifying transaction with fee

### ISSUE THREAD

**Issue by enzoc4** [input-output-hk/jormungandr#449]
**Describe the bug**

What I think is a valid transaction is not getting accepted by the node when using fees.

**To Reproduce**

I'm creating a transaction with the following commands

```sh
jcli transaction new > tx
jcli transaction add-input 55762218e5737603e6d27d36c8aacf8fcd16406e820361a8ac65c7dc663f6d1c 0 1000000000000 --staging tx
jcli transaction add-output $(cat address) 10000 --staging tx
jcli transaction finalize ta1sn9u0nxmnfg7af8ycuygx57p5xgzmnmgtaeer9xun7hly6mlgt3pjp0h0rrq782p7z4auve0s4l72egyc88f49mzm8lwuaw7xnw52udky79t3s --fee-coefficient 8 --fee-constant 10 --staging tx
```

Transaction info shows the following (implying the transaction is balanced actually balanced)

```sh
jcli transaction info --fee-coefficient 8 --fee-constant 10 --staging
>>>
txTransaction `de27321313dfe713b530266dd912c4ffee1ab822ec5df6b40d51a900e2d047ad' (finalizing)
  Input:   1000000000000
  Output:  999999999966
  Fees:    34
  Balance: 0
 - 55762218e5737603e6d27d36c8aacf8fcd16406e820361a8ac65c7dc663f6d1c:0 1000000000000
 + ta1ssnr5pvt9e5p009strshxndrsx5etcentslp2rwj6csm8sfk24a2wu27hujgyzl4mlc736jaztykud5tqrxw5gd6esmw7rx5zujdzw3ahcaskk 10000
 + ta1sn9u0nxmnfg7af8ycuygx57p5xgzmnmgtaeer9xun7hly6mlgt3pjp0h0rrq782p7z4auve0s4l72egyc88f49mzm8lwuaw7xnw52udky79t3s 999999989966
```

I have this in the genesis config
```yaml
  linear_fee:
    constant: 10
    coefficient: 8
    certificate: 0
```
After signing it and sending it to the node, I'm getting the following error from the logs of the rest api

```
- fragment_id: 8ca71424b2e7494d5f7bfd1c1b2cf5154b7468a439e99449a9023ef29b103c1e
  last_updated_at: "2019-06-10T18:51:37.035303063Z"
  received_at: "2019-06-10T18:50:57.470363704Z"
  received_from: Rest
  status:
    Rejected:
      reason: "Inputs, outputs and fees are not balanced, transaction with 1000000000000 input and 1000000000034 output"
```

**Expected behavior**
The transaction gets accepted in block. 

**Additional context**

I'm not getting this error when not setting fees (constant 0, coefficient 0), and I think the problem may be that the validation is checking inputs == inputs + fee in [this line](https://github.com/input-output-hk/rust-cardano/blob/6991be0ea796abee4418d1143b5a36065884d2b0/chain-impl-mockchain/src/ledger.rs#L620) but I may be wrong
