### ISSUE TITLE
blockchain_configuration: linear_fee or linear_fees

### ISSUE THREAD

**Issue by rinor** [input-output-hk/jormungandr#466]
**Describe the bug**
Under *blockchain_configuration* the *linear_fee* option is generated as _linear_fee_**s** from the bootstrap script.

**To Reproduce**
1. Run _boostrap_ script
2. check _genesis.yaml_ file
```
blockchain_configuration:
...
  linear_fees:
    constant: 10
    coefficient: 0
    certificate: 0
...
```
**Expected behavior**
```
blockchain_configuration:
...
  linear_fee:
    constant: 10
    coefficient: 0
    certificate: 0
...
```
