### ISSUE TITLE
jcli: Improve the response of "jcli rest v0 message logs"

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#507]
**Describe the bug**
After creating some transactions, if we execute "jcli rest v0 message logs" we can see if the transaction was Accepted or not (the Status). It would be more than useful to have more details inside the response - like the TransactionID

**To Reproduce**
1. Create some transactions and wait for them to be accepted by the node
2. execute "jcli rest v0 message logs --host http://127.0.0.1:8607/api"
```
---
- fragment_id: de05f97b5e10ed4182493972b8b5158952ce69cef0f4af0727dcb7d49b05dbd0
  last_updated_at: "2019-06-17T06:49:21.010505100Z"
  received_at: "2019-06-17T06:49:20.681866600Z"
  received_from: Rest
  status:
    InABlock: "0.32"
- fragment_id: 66a34e9cf6a7abacca602a487621c90a54d92863408eafe2915c1e6480e868da
  last_updated_at: "2019-06-17T06:46:41.004386800Z"
  received_at: "2019-06-17T06:46:36.221886800Z"
  received_from: Rest
  status:
    InABlock: "0.16"
```

**Expected behavior**
You should be able to see what exactly was accepted by the node -> in this case, the Transaction ID/hash would be more than necessary 

**Additional context**
