### ISSUE TITLE
block0 initial funds should accept multiple entries

### ISSUE THREAD

**Issue by vincenthz** [input-output-hk/jormungandr#579]
fund and legacy_funds are currently defined as single entry, where they should be multiples

so moving from:

```
fund:
  address: ...
  entry: ...
```

to:

```
fund:
   - address: ...
      entry: ...
   - address: ...
      entry: ...
```
