### ISSUE TITLE
Transactions are rejected when genesis file is re-encoded manually

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#610]
**Describe the bug**
Send funds transactions are rejected with `Account with invalid signature` when genesis.yaml is re-encoded manually. 

**To Reproduce**
1. create files with *bootstrap* script: `bash bootstrap -p 8607 -g -s 2`
2. modify `slots_per_epoch: 20` inside *genesis.yaml*
3. encode the genesis.yaml: `jcli genesis encode --input genesis.yaml --output block-0.bin`
4. start the node: `jormungandr --genesis-block ./block-0.bin --config ./config.yaml --secret ./pool-secret1.yaml`
5. create an Account address
6. send funds from Faucet to previously created Account: `bash faucet-send-money.sh <ACCOUNT_ADDRESS> 1111`
7. wait for a new block to be created
8. check node logs -> transaction is rejected  - `reason: Account with invalid signature`
```
$ jcli rest v0 message logs -h "${REST_URL}"
---
- fragment_id: fb1b404b3e2c95733d72a1ef8cd50ba1f8850492fa44baa050c14e56edce8c32
  last_updated_at: "2019-07-05T10:26:35.007415600+00:00"
  received_at: "2019-07-05T10:26:32.331265500+00:00"
  received_from: Rest
  status:
    Rejected:
      reason: Account with invalid signature
```

**Expected behavior**
Everything should be fine - Transaction should be included in a block.

**Additional context**
If I execute the same steps with the default values (`slots_per_epoch: 5000`) everything is fine.
If I don't execute step 3, the change from step 2 will not have any effect after starting the node.

[nodeLogs.txt](https://github.com/input-output-hk/jormungandr/files/3362281/nodeLogs.txt)
[clientLogs.txt](https://github.com/input-output-hk/jormungandr/files/3362282/clientLogs.txt)

**Comment by rinor** [comment]
**os**: `Linux 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux`
**rustc --version**: `rustc 1.36.0 (a53f9df32 2019-07-03)`
**node build from**: b7f2f847ee73f79e81d7762f4f38ad8fcac17c75
```
########################################################

* Consensus      : genesis_praos
* REST Port      : 8443
* Slot duration  : 2
* Slots per epoch: 20

########################################################

* CLI  version: jcli 0.2.4
* NODE version: jormungandr 0.2.4

########################################################
```
I **can not** replicate the issue. The transactions are accepted as usual (bft and genesis_praos).  Will continue testing...

```
- fragment_id: ae115652c46a35e6987486ffb10ee9981265dfc70617bddc1f4b362ba8abeee4
  last_updated_at: "2019-07-05T14:06:26.014071522+00:00"
  received_at: "2019-07-05T14:05:55.006420978+00:00"
  received_from: Rest
  status:
    InABlock:
      date: "17.18"
- fragment_id: 4b3da029d9018ee40868d05c998cbfe11c52091ff676888d5f6d8cc2bdc0a5c5
  last_updated_at: "2019-07-05T14:05:50.004048874+00:00"
  received_at: "2019-07-05T14:05:42.544214929+00:00"
  received_from: Rest
  status:
    InABlock:
      date: "17.0"
- fragment_id: a673f2f004b7ac387466f8da47d3d84a9d6f004929f9669e53ab5f69c482f2b5
  last_updated_at: "2019-07-05T14:05:04.014146885+00:00"
  received_at: "2019-07-05T14:05:03.082441192+00:00"
  received_from: Rest
  status:
    InABlock:
      date: "15.17"
...
```
