### ISSUE TITLE
[Jormungandr] - [mempool] : Node "stops" producing blocks if garbage_collection_interval < fragment_ttl

### ISSUE THREAD

**Issue by rinor** [input-output-hk/jormungandr#705]
**Describe the bug**
Node "stops" producing blocks if _garbage_collection_interval_ **<** _fragment_ttl_
and at least 1 transaction is sent/confirmed before _garbage_collection_interval_

**To Reproduce**
1. Start the node having the new config as below.
2. Send a transaction.
3. After _garbage_collection_interval_ no more blocks produced.
```
mempool:
    fragment_ttl: 30m
    log_ttl: 1h
    garbage_collection_interval: 15m
```
**Additional context**
if _garbage_collection_interval_ **>** _fragment_ttl_ all looks fine
```
mempool:
    fragment_ttl: 30m
    log_ttl: 1h
    garbage_collection_interval: 31m
```
