### ISSUE TITLE
Unwrap fails in network::grpc::client::connect

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#803]
**Describe the bug**
I am receiving this error when starting the node (connected to the devops testnet).

**Mandatory Information**
`jcli 0.3.9999 (heads/v0.3.9999-d6e8fabf, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]`
`jormungandr 0.3.9999 (heads/v0.3.9999-d6e8fabf, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]`

**To Reproduce**
1. start local node using trusted-peers and genesis-hash provided by devops (attached) - `jormungandr ---config node_config.yaml --genesis-block-hash f40001894fec0a93a754ff7cdc125ed64fc88260f575f9971b98ee85a35750b6` 

**Expected behavior**
Node successfully starts and sync to the blockchain.

**Additional context**
Local node config:
```
rest:
  listen: "127.0.0.1:8000"
p2p:
  public_address: /ip4/5.xx.xx.xx/tcp/3000
  listen_address: /ip4/192.168.100.13/tcp/3000
  trusted_peers: [XXXXX]
  topics_of_interest:
    messages: high
    blocks: high
```

![image](https://user-images.githubusercontent.com/29144964/65416480-9e607a80-de00-11e9-8a0a-6707c84ead2d.png)

Local node logs:
[local_node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3641548/local_node_logs.txt)
