### ISSUE TITLE
(documentation) Update the documentation for `jcli certificate new stake-pool-registration` 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#832]
**Describe the bug**
There were added new mandatory parameters to `jcli certificate new stake-pool-registration` that are not documented in the official documentation (https://input-output-hk.github.io/jormungandr/stake_pool/registering_stake_pool.html#creating-your-stake-pool-certificate)

**Mandatory Information**
```
jormungandr 0.5.0 (HEAD-98922c77, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
jcli 0.5.0 (HEAD-98922c77, release, windows [x86_64]) - [rustc 1.36.0 (a53f9df32 2019-07-03)]
```

**To Reproduce**
1. https://input-output-hk.github.io/jormungandr/stake_pool/registering_stake_pool.html#creating-your-stake-pool-certificate

```
$ jcli certificate new stake-pool-registration --kes-key ${POOL_KES_PK} --vrf-key ${POOL_VRF_PK} --serial 1010101010 > stake_pool.cert
error: The following required arguments were not provided:
    --start-validity <SECONDS-SINCE-START>
    --management-threshold <THRESHOLD>

USAGE:
    jcli.exe certificate new stake-pool-registration [OPTIONS] --kes-key <KES_KEY> --start-validity <SECONDS-SINCE-START> --serial <SERIAL> --management-threshold <THRESHOLD> --vrf-key <VRF_KEY> [--] [output]

For more information try --help
```

**Expected behavior**
All command parameters are clearly described in the official documentation. A correct and functional example should also be provided. 

**Additional context**
It seems that the certificate is not created correctly also if we don't use `--owner` parameter so I suppose this should be mandatory too. (and documented)

**Comment by dorin100** [comment]
When I am trying to create a stake pool using some random values for `--start-validity` and `--management-threshold`, the transaction for submitting the stake pool registration certificate is rejected as below. I am not sure that the values of the 2 parameters is causing it but it can be.

```jcli certificate new stake-pool-registration --kes-key ${POOL_KES_PK} --vrf-key ${POOL_VRF_PK} --serial 1010101010 --start-validity 1000000 --management-threshold 10 > stake_pool.cert```

```
fragment_id: 2508faa998eb8e6486e616cc07055b66f1f7c3afaf2a993d16d4ca50f5e3475c
  last_updated_at: "2019-09-25T13:38:31.002804300+00:00"
  received_at: "2019-09-25T13:38:28.164952300+00:00"
  received_from: Network
  status:
    Rejected:
      reason: Pool Registration certificate invalid
```
