### ISSUE TITLE
All the transactions remain in `Pending`

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#844]
**Describe the bug**
All the transactions(transfer funds, send certificate, delegate, etc) are remaining in `Pending` even multiple new blocks are created. Only the transaction from getting money from web faucet are included in a block.

**Mandatory Information**
```
jcli 0.5.2 (HEAD-e7a3efe7, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
jormungandr 0.5.2 (HEAD-e7a3efe7, release, windows [x86_64]) - [rustc 1.37.0 (eae3437df 2019-08-13)]
```

**To Reproduce**
1. start the node using: `jormungandr ---config node_config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770`
2. extract the attached archive into the same folder with the node config
3. execute the create account and delegate script: `bash create-account-and-delegate.sh`
- the same scripts worked until v0.5.0
- I updated the genesis_hash, faucet private key (with personal account details with funds) and stakePoolID with valid values --> the transactions are correctly created but they remain in `Pending`
4. wait for at least 1 new block to be created and check node stats and logs --> all the transactions are remaining stuck in `Pending`

**Expected behavior**
All the transactions should be executed - be included in a block or rejected with a valid message/reason. 

**Additional context**
- OS: win 10; local node has an open connection with the outside/internet
- node logs:
[node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3661295/node_logs.txt)

![image](https://user-images.githubusercontent.com/29144964/65748250-25b53300-e10c-11e9-8311-85c3d7781b81.png)

- script execution logs:
[account_delegation_script_logs.txt](https://github.com/input-output-hk/jormungandr/files/3661281/account_delegation_script_logs.txt)

- scripts_used: 
[scripts_used.zip](https://github.com/input-output-hk/jormungandr/files/3661275/scripts_used.zip)

- node config
```
rest:
  listen: "127.0.0.1:9000"
p2p:
  public_address: /ip4/5.12.xx.xx/tcp/3000
  listen_address: /ip4/192.168.xx.xx/tcp/3000
  trusted_peers: [/ip4/3.123.177.192/tcp/3000,
                  /ip4/3.123.155.47/tcp/3000,
                  /ip4/52.57.157.167/tcp/3000,
                  /ip4/3.112.185.217/tcp/3000,
                  /ip4/18.140.134.230/tcp/3000,
                  /ip4/18.139.40.4/tcp/3000,
                  /ip4/3.115.57.216/tcp/3000]
  topics_of_interest:
    messages: high
    blocks: high
```

**Comment by rdlrt** [comment]
You've probably checked, but just for completion... do the fee/cert constants in the script match the node settings?

**Comment by dorin100** [comment]
Hi @rdlrt . You are right, the fees were updated and there were different from the ones from my scripts. Anyway, I updated the scripts with the nee fee values but the behavior is the same.

**Comment by dorin100** [comment]
Ok. this seems related to the fees. So if the correct fees are provided for each type of transaction, then everything is ok.

The user experience is still lacking when the transaction is Rejected because this info is not propagated back to the initiator that can only see a transaction with `Status: Pending`

**Comment by NicolasDP** [comment]
did you look at the configuration for the mempool ?

```yaml
mempool:
    # this value sets for how long your fragment logs will stay
    log_ttl: 1h
    # this value sets for how long the fragment will remaining pending at most
    fragment_ttl: 20m
    # this will ask the node to perform garbage collection on the logs and fragment every...
    garbage_collection_interval: 20m
```

**Comment by dkijania** [comment]
I'm also experiencing mentioned issue on 0.5.2 on my local private testnet. I'm sure fragment is correct:

```
λ jcli rest v0 message logs -h http://127.0.0.1:8000/api
---
- fragment_id: d7df73a5959ac6dcce4765b42c4f483d13c77add23b70f94bb1a39111946fb50
  last_updated_at: "2019-09-28T13:07:48.714351600+00:00"
  received_at: "2019-09-28T13:07:48.714351600+00:00"
  received_from: Rest
  status: Pending

C:\Work\iohk\jormungandr\jormungandr-scenario-tests (jts -> origin)
λ jcli rest v0 message logs -h http://127.0.0.1:8001/api
---
- fragment_id: d7df73a5959ac6dcce4765b42c4f483d13c77add23b70f94bb1a39111946fb50
  last_updated_at: "2019-09-28T13:08:01.008176200+00:00"
  received_at: "2019-09-28T13:07:48.718354600+00:00"
  received_from: Network
  status:
    InABlock:
      date: "0.23"
```
The fragment is in pending state for more than 10 mins.
This issue was fix already in 0.3.x version i believe and looks like
