### ISSUE TITLE
File descriptor limit exhausted (ERRO cannot send PullHeaders request to network: send failed because receiver is gone, task: block)

### ISSUE THREAD

**Issue by bjarnekvae** [input-output-hk/jormungandr#872]
**Describe the bug**
Log is spammed by:
ERRO cannot send PullHeaders request to network: send failed because receiver is gone, task: block

Block counter seems to stop

**Mandatory Information**
1. `jcli --full-version` output;
jcli 0.5.4 (HEAD-a9ec5ce, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

2. `jormungandr --full-version` output;
jormungandr 0.5.4 (HEAD-a9ec5ce, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**
The error started after aproximated 56949s of uptime

**Expected behavior**
Expected to keep receiving blocks

**Additional context**
Config:
```
log:
  format: "plain"
  level: "info"
  output: "stderr"
p2p:
  listen_address: "/ip4/0.0.0.0/tcp/3000"
  public_address: "/ip4/x.x.x.x/tcp/3000"
  topics_of_interest:
    blocks: "high"
    messages: "high"
  trusted_peers:
    - "/ip4/3.123.177.192/tcp/3000"
    - "/ip4/3.123.155.47/tcp/3000"
    - "/ip4/52.57.157.167/tcp/3000"
    - "/ip4/3.112.185.217/tcp/3000"
    - "/ip4/18.140.134.230/tcp/3000"
    - "/ip4/18.139.40.4/tcp/3000"
    - "/ip4/3.115.57.216/tcp/3000"
rest:
  listen: "127.0.0.1:3101"
storage: "/tmp/jormungandr"
```

Please se attached log
[node_log_erroPullHeader.log](https://github.com/input-output-hk/jormungandr/files/3675901/node_log_erroPullHeader.log)
