### ISSUE TITLE
(enhancement) Enhance the output of `rest v0 settings get` command

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#884]
**Describe the bug**
It would be useful to have `slot_duration` and `slots_per_epoch` displayed in the output of `rest v0 settings get` command (especially when using local scripts for different actions).

**Additional context**
```
$ Jcli rest v0 settings get --host "http://127.0.0.1:9000/api"
---
block0Hash: adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
block0Time: "2019-02-22T07:53:34+00:00"
consensusVersion: genesis
currSlotStartTime: "2019-10-02T11:19:58+00:00"
fees:
  certificate: 10000
  coefficient: 50
  constant: 1000
maxTxsPerBlock: 255
```

**Comment by rinor** [comment]
You mean smth like this:
```
---
block0Hash: dc47d16e0f5c56db286ec9bf2927dfcc5d493a1307bdb0fa5a66d041ba8256b2
block0Time: "2017-09-29T00:00:00+00:00"
consensusVersion: genesis
currSlotStartTime: "2019-10-02T14:13:30+00:00"
fees:
  certificate: 10000
  coefficient: 50
  constant: 10
maxTxsPerBlock: 255
slotDuration: 10
slotsPerEpoch: 1
```
anything else to be added?
