### ISSUE TITLE
genesis encode has an declaration order dependency between funds and delegation certificates

### ISSUE THREAD

**Issue by rinor** [input-output-hk/jormungandr#917]
**Describe the bug**
`jcli genesis encode --input block0.yaml` fails if we have **delegation certificates declared before funds** for addresses involved in that delegation.

**Mandatory Information**
1. `jcli 0.5.6+lock (master-f0e869c2, debug, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]`
2. `jormungandr 0.5.6+lock (master-5ddbe918, debug, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]`

**To Reproduce**
This config order fails
```
initial:
  - cert: cert1qvqqqqqqqqqqqqqqqqqqq7rf6cjqqqqqqqqqqqqqqqqsqqg8dhqnq8mf306k939kmh0f8pcwxr685v47fzsx0gprz43v82pcqcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqqqqqqqqqqqp3khwvrtgrdzy3w6mmeleh83qsutr3ad72azcyg3zpqfawgzn3t2ep2ce7kdkv8synnm72her593m9reu8e99xnjezlqajj6jl5y7xlqjgl538
  - cert: cert1qyrkmsfsra5chatzcjmdmh5nsu8rpar6x2ly3gr85q332ckr4quqvm4d8ffvv68y7cte0qepszjevag90lsecahezjjpwkajy7w9sdvqf8culd
  - fund:
      - address: jnode_ta1s5rkmsfsra5chatzcjmdmh5nsu8rpar6x2ly3gr85q332ckr4quqvy8sthh
        value: 1000000000000
```

with error:

```
[generated block is not a valid genesis block
  |-> Error or Invalid account
  |-> Account does not exist] -> exit status 1
```

**Expected behavior**
No failure.

**Additional context**
The same config data, but reordered, work fine:
```
initial:
  - fund:
      - address: jnode_ta1s5rkmsfsra5chatzcjmdmh5nsu8rpar6x2ly3gr85q332ckr4quqvy8sthh
        value: 1000000000000
  - cert: cert1qvqqqqqqqqqqqqqqqqqqq7rf6cjqqqqqqqqqqqqqqqqsqqg8dhqnq8mf306k939kmh0f8pcwxr685v47fzsx0gprz43v82pcqcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqqqqqqqqqqqp3khwvrtgrdzy3w6mmeleh83qsutr3ad72azcyg3zpqfawgzn3t2ep2ce7kdkv8synnm72her593m9reu8e99xnjezlqajj6jl5y7xlqjgl538
  - cert: cert1qyrkmsfsra5chatzcjmdmh5nsu8rpar6x2ly3gr85q332ckr4quqvm4d8ffvv68y7cte0qepszjevag90lsecahezjjpwkajy7w9sdvqf8culd
```
```
initial:
  - cert: cert1qvqqqqqqqqqqqqqqqqqqq7rf6cjqqqqqqqqqqqqqqqqsqqg8dhqnq8mf306k939kmh0f8pcwxr685v47fzsx0gprz43v82pcqcqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqpqqqqqqqqqqqqp3khwvrtgrdzy3w6mmeleh83qsutr3ad72azcyg3zpqfawgzn3t2ep2ce7kdkv8synnm72her593m9reu8e99xnjezlqajj6jl5y7xlqjgl538
  - fund:
      - address: jnode_ta1s5rkmsfsra5chatzcjmdmh5nsu8rpar6x2ly3gr85q332ckr4quqvy8sthh
        value: 1000000000000
  - cert: cert1qyrkmsfsra5chatzcjmdmh5nsu8rpar6x2ly3gr85q332ckr4quqvm4d8ffvv68y7cte0qepszjevag90lsecahezjjpwkajy7w9sdvqf8culd
```
---
**labels**:"Priority - Low"
