### ISSUE TITLE
have private_id in a different file

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/jormungandr#942]
currently the private node id is in the config file, this will need to move in a separate file *before* cryptography is in use.

**Comment by rinor** [comment]
If we have the file **/path/to/private_id/file** containing the private_id (secret key),
what would be the preferred content format?
1) **simple** one
```
ed25519_sk19p5jpexh54p3yyv9k6fspu7t3874hj0rnufhx6fv47nn204umqmq658xcx
```
2) **key: val** one
```
private_id: ed25519_sk19p5jpexh54p3yyv9k6fspu7t3874hj0rnufhx6fv47nn204umqmq658xcx
```

what would be the preferred way to include that file in the config?
1) include the *file path* to the existing config insided **p2p** section?
```
p2p:
  private_id: /path/to/private_id/file
  public_address: /ip4/127.0.0.11/tcp/9001
  listen_address: /ip4/127.0.0.11/tcp/9001
  topics_of_interest:
    messages: high
    blocks: high
  max_connections: 256
  allow_private_addresses: true
```
2) pass the *file path* as a command line argument to jörmungandr:
```
jormungandr --private-id=/path/to/private_id/file .....
```
3) both (1) and (2) with (2) having higher priority?
