### ISSUE TITLE
thread 'network0INFO' panicked at 'Box<Any> 

### ISSUE THREAD

**Issue by dorin100** [input-output-hk/jormungandr#952]
**Describe the bug**
Node crashed at startup - using `v0.6.0`, release files for windows.

**Mandatory Information**
```
jcli 0.6.0 (HEAD-44ff7c1e, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jormungandr 0.6.0 (HEAD-44ff7c1e, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
```

**To Reproduce**
1. start the passive node using: `jormungandr ---config node_config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770`

**Expected behavior**
The node starts successfully.

**Additional context**
- OS: Windows x64
- Ports are not open/forwarded
- node logs:
[node_logs.txt](https://github.com/input-output-hk/jormungandr/files/3727655/node_logs.txt)
```
Oct 15 09:23:54.577 thread 'network0INFO' panicked at 'Box<Any> ', start listening and accepting gRPC connections on 5.12.XX.XX:3000jormungandr\src\main.rs, :225task:30:
stack backtrace:
 network
Oct 15 09:23:54.579 ERRO failed to listen for P2P connections at 5.12.XX.XX:3000, reason: failed to listen for connections on 5.12.XX.XX:3000, task: network
Oct 15 09:23:54.583 INFO Starting 1 workers, scope: global
Oct 15 09:23:54.586 INFO Starting server on 127.0.0.1:9000, scope: global
   0:           0x7d63e3 - backtrace::backtrace::dbghelp::trace::h5e9d2eba4720b7ac
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.34\src\backtrace/dbghelp.rs:88
   1:           0x7d63e3 - backtrace::backtrace::trace_unsynchronized::hd2d1bfb115460c6d
                               at C:\Users\VssAdministrator\.cargo\registry\src\github.com-1ecc6299db9ec823\backtrace-0.3.34\src\backtrace/mod.rs:66
   2:           0x7d63e3 - std::sys_common::backtrace::_print::hd03fe26089330b90
                               at src\libstd\sys_common/backtrace.rs:47
   3:           0x7d63e3 - std::sys_common::backtrace::print::h7a0ffa165d6e65e6
                               at src\libstd\sys_common/backtrace.rs:36
   4:           0x7d63e3 - std::panicking::default_hook::{{closure}}::hc4b8a134a08c99d0
                               at src\libstd/panicking.rs:200
   5:           0x7d55ea - std::panicking::default_hook::h555d420ce189cd9c
                               at src\libstd/panicking.rs:214
   6:           0x7d55ea - std::panicking::rust_panic_with_hook::h5ee54dc12c495453
                               at src\libstd/panicking.rs:477
   7:           0x4052c4 - std::panicking::begin_panic::hc810dfc43de138a6
   8:           0x9fa61e - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h4ded97c65c1eb1d8
   9:           0x7ba27c - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hc699b47f53ecf30d
  10:           0x7bdae3 - tokio_threadpool::worker::Worker::run_task::h24bc6af519f4b63f
  11:           0x7bbc48 - tokio_threadpool::worker::Worker::run::h4b45d7f219e2b4d8
  12:           0x79f846 - std::thread::local::LocalKey<T>::with::hd14c3674ec23e082
  13:           0x7a3041 - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h263ae8f4c9faa860
  14:           0x7b97e4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h97585d8bad4ccb70
  15:           0x7ba692 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h1394d9cecf6e852c
  16:           0x7e7536 - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::he13a04fb600ff287
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\liballoc/boxed.rs:787
  17:           0x7e8b3c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::hb8c868d75fab1423
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54\src\liballoc/boxed.rs:787
  18:           0x7e8b3c - std::sys_common::thread::start_thread::h1d84a837f703e334
                               at src\libstd\sys_common/thread.rs:13
  19:           0x7e8b3c - std::sys::windows::thread::Thread::new::thread_start::h3eed3e0632115ee6
                               at src\libstd\sys\windows/thread.rs:47
  20:     0x7ffbc9137bd4 - _rbt_backtrace_dwarf_add.cold
  21:     0x7ffbcabaced1 - _rbt_backtrace_dwarf_add.cold
```
- node config
```
---
log:
  format: plain
  level: info
  output: stderr
rest:
  listen: "127.0.0.1:9000"
p2p:
  public_address: /ip4/5.12.114.32/tcp/3000
  private_id: ed25519_sk10hl0n8fac5ls7ldmydmx6fk4rl7ejhjv66uyvkdtlxexsf39cyssxkmc6s
  trusted_peers:
    - address: "/ip4/3.115.194.22/tcp/3000"
      id: ed25519_pk1npsal4j9p9nlfs0fsmfjyga9uqk5gcslyuvxy6pexxr0j34j83rsf98wl2
    - address: "/ip4/13.113.10.64/tcp/3000"
      id: ed25519_pk16pw2st5wgx4558c6temj8tzv0pqc37qqjpy53fstdyzwxaypveys3qcpfl
    - address: "/ip4/52.57.214.174/tcp/3000"
      id: ed25519_pk1v4cj0edgmp8f2m5gex85jglrs2ruvu4z7xgy8fvhr0ma2lmyhtyszxtejz
    - address: "/ip4/3.120.96.93/tcp/3000"
      id: ed25519_pk10gmg0zkxpuzkghxc39n3a646pdru6xc24rch987cgw7zq5pmytmszjdmvh
    - address: "/ip4/52.28.134.8/tcp/3000"
      id: ed25519_pk1unu66eej6h6uxv4j4e9crfarnm6jknmtx9eknvq5vzsqpq6a9vxqr78xrw
    - address: "/ip4/13.52.208.132/tcp/3000"
      id: ed25519_pk15ppd5xlg6tylamskqkxh4rzum26w9acph8gzg86w4dd9a88qpjms26g5q9
    - address: "/ip4/54.153.19.202/tcp/3000"
      id: ed25519_pk1j9nj2u0amlg28k27pw24hre0vtyp3ge0xhq6h9mxwqeur48u463s0crpfk
explorer:
  enabled: true
storage: "./storage"
```
