### ISSUE TITLE
Receiving on a closed channel

### ISSUE THREAD

**Issue by javierjmc** [input-output-hk/jormungandr#980]
**Describe the bug**
Tried to run a node, then after some initial bootstrapping, the client crashed.

**Mandatory Information**
1. jcli 0.6.1 (HEAD-a0de8d4, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. jormungandr 0.6.1 (HEAD-a0de8d4, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

`node_config.yaml`:
```
storage: "/tmp/jormungandr"
log:
  level: info
  format: json
  output: stderr
p2p:
  trusted_peers:
    - address: "/ip4/3.115.194.22/tcp/3000"
      id: ed25519_pk1npsal4j9p9nlfs0fsmfjyga9uqk5gcslyuvxy6pexxr0j34j83rsf98wl2
    - address: "/ip4/13.113.10.64/tcp/3000"
      id: ed25519_pk16pw2st5wgx4558c6temj8tzv0pqc37qqjpy53fstdyzwxaypveys3qcpfl
    - address: "/ip4/52.57.214.174/tcp/3000"
      id: ed25519_pk1v4cj0edgmp8f2m5gex85jglrs2ruvu4z7xgy8fvhr0ma2lmyhtyszxtejz
    - address: "/ip4/3.120.96.93/tcp/3000"
      id: ed25519_pk10gmg0zkxpuzkghxc39n3a646pdru6xc24rch987cgw7zq5pmytmszjdmvh
    - address: "/ip4/52.28.134.8/tcp/3000"
      id: ed25519_pk1unu66eej6h6uxv4j4e9crfarnm6jknmtx9eknvq5vzsqpq6a9vxqr78xrw
    - address: "/ip4/13.52.208.132/tcp/3000"
      id: ed25519_pk15ppd5xlg6tylamskqkxh4rzum26w9acph8gzg86w4dd9a88qpjms26g5q9
    - address: "/ip4/54.153.19.202/tcp/3000"
      id: ed25519_pk1j9nj2u0amlg28k27pw24hre0vtyp3ge0xhq6h9mxwqeur48u463s0crpfk

  public_address: "/ip4/127.0.0.1/tcp/8080"
  private_id: ed25519_sk1n649x7zrmt38q6dtqkvj769wru4vpkfnrppw6d83qd7jh3uhux7qwhg8q3
  topics_of_interest:
    messages: low
    blocks: normal
rest:
  listen: "127.0.0.1:8080"
```

**To Reproduce**
1. Config a node_config.yaml.
2. run `RUST_BACKTRACE=full ./jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770`
3. Wait
4. Crash

**Expected behavior**
Sync node

**Additional context**
My system:
Here's the output:
```
{"msg":"Starting jormungandr 0.6.1 (HEAD-a0de8d4, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]","level":"INFO","ts":"2019-10-18T07:58:38.758208977+02:00","task":"init"}
{"msg":"Node started without path to the stored secret keys (not a stake pool or a BFT leader)","level":"WARN","ts":"2019-10-18T07:58:38.758664875+02:00","task":"init"}
{"msg":"storing blockchain in '\"/tmp/jormungandr/blocks.sqlite\"'","level":"INFO","ts":"2019-10-18T07:58:38.758824682+02:00","task":"init"}
{"msg":"connecting to bootstrap peer 13.52.208.132:3000","level":"INFO","ts":"2019-10-18T07:59:37.325059034+02:00","peer_addr":"13.52.208.132:3000","task":"bootstrap"}
{"msg":"with initial bootstrap","level":"WARN","ts":"2019-10-18T07:59:38.803841745+02:00","peer_addr":"13.52.208.132:3000","task":"bootstrap","reason":"bootstrap pull stream failed"}
{"msg":"connecting to bootstrap peer 13.113.10.64:3000","level":"INFO","ts":"2019-10-18T07:59:38.803970013+02:00","peer_addr":"13.113.10.64:3000","task":"bootstrap"}
{"msg":"with initial bootstrap","level":"WARN","ts":"2019-10-18T07:59:39.423076265+02:00","peer_addr":"13.113.10.64:3000","task":"bootstrap","reason":"bootstrap pull stream failed"}
{"msg":"connecting to bootstrap peer 52.28.134.8:3000","level":"INFO","ts":"2019-10-18T07:59:39.423627343+02:00","peer_addr":"52.28.134.8:3000","task":"bootstrap"}
{"msg":"with initial bootstrap","level":"WARN","ts":"2019-10-18T07:59:39.484504695+02:00","peer_addr":"52.28.134.8:3000","task":"bootstrap","reason":"bootstrap pull stream failed"}
{"msg":"connecting to bootstrap peer 3.120.96.93:3000","level":"INFO","ts":"2019-10-18T07:59:39.485097325+02:00","peer_addr":"3.120.96.93:3000","task":"bootstrap"}
{"msg":"with initial bootstrap","level":"WARN","ts":"2019-10-18T07:59:39.543898676+02:00","peer_addr":"3.120.96.93:3000","task":"bootstrap","reason":"bootstrap pull stream failed"}
{"msg":"connecting to bootstrap peer 3.115.194.22:3000","level":"INFO","ts":"2019-10-18T07:59:39.544015974+02:00","peer_addr":"3.115.194.22:3000","task":"bootstrap"}
{"msg":"with initial bootstrap","level":"WARN","ts":"2019-10-18T07:59:41.059162532+02:00","peer_addr":"3.115.194.22:3000","task":"bootstrap","reason":"bootstrap pull stream failed"}
{"msg":"connecting to bootstrap peer 52.57.214.174:3000","level":"INFO","ts":"2019-10-18T07:59:41.059603923+02:00","peer_addr":"52.57.214.174:3000","task":"bootstrap"}
{"msg":"with initial bootstrap","level":"WARN","ts":"2019-10-18T07:59:41.118088601+02:00","peer_addr":"52.57.214.174:3000","task":"bootstrap","reason":"bootstrap pull stream failed"}
{"msg":"connecting to bootstrap peer 54.153.19.202:3000","level":"INFO","ts":"2019-10-18T07:59:41.118489391+02:00","peer_addr":"54.153.19.202:3000","task":"bootstrap"}
{"msg":"with initial bootstrap","level":"WARN","ts":"2019-10-18T07:59:41.772963582+02:00","peer_addr":"54.153.19.202:3000","task":"bootstrap","reason":"bootstrap pull stream failed"}
{"msg":"starting task","level":"INFO","ts":"2019-10-18T07:59:41.773644228+02:00","task":"client-query"}
{"msg":"adding P2P Topology module: trusted-peers","level":"INFO","ts":"2019-10-18T07:59:41.773894292+02:00","task":"network"}
{"msg":"start listening and accepting gRPC connections on 127.0.0.1:8080","level":"INFO","ts":"2019-10-18T07:59:41.773996465+02:00","task":"network"}
{"msg":"connecting to initial gossip peer","level":"INFO","ts":"2019-10-18T07:59:41.774171618+02:00","peer_addr":"52.57.214.174:3000","task":"network"}
{"msg":"connecting to initial gossip peer","level":"INFO","ts":"2019-10-18T07:59:41.774310324+02:00","peer_addr":"3.115.194.22:3000","task":"network"}
{"msg":"connecting to initial gossip peer","level":"INFO","ts":"2019-10-18T07:59:41.774636330+02:00","peer_addr":"13.113.10.64:3000","task":"network"}
{"msg":"connecting to initial gossip peer","level":"INFO","ts":"2019-10-18T07:59:41.775048133+02:00","peer_addr":"52.28.134.8:3000","task":"network"}
thread 'leadership0' panicked at 'Expect the event to not close', src/libcore/option.rs:1166:5
stack backtrace:
{"msg":"Shutting down service client-query (up since 544ms 473us 294ns): receiving on a closed channel","level":"WARN","ts":"2019-10-18T07:59:42.318075160+02:00","task":"client-query"}
   0:     0x55c0dc617f58 - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x55c0dc617f58 - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x55c0dc617f58 - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x55c0dc617f58 - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x55c0dc617f58 - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x55c0dc6176a7 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x55c0dc6176a7 - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x55c0dc6171cf - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x55c0dc625ce6 - rust_begin_unwind
                               at src/libstd/panicking.rs:311
   9:     0x55c0dc630ccc - core::panicking::panic_fmt::h7e9f94035af782b3
                               at src/libcore/panicking.rs:85
  10:     0x55c0dc636e76 - core::option::expect_failed::h292a6217b603c24f
                               at src/libcore/option.rs:1166
  11:     0x55c0dc2713eb - futures::future::chain::Chain<A,B,C>::poll::h27f95323f58f2f6d
  12:     0x55c0dc688b1b - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h3711bd19806ddeb8
  13:     0x55c0dc60cbb0 - futures::task_impl::std::set::he6c155cd71518697
  14:     0x55c0dc608ba9 - tokio_threadpool::worker::Worker::run_task::h1a928c93437110f5
  15:     0x55c0dc606ee0 - tokio_threadpool::worker::Worker::run::h127f571d23884c72
  16:     0x55c0dc5edd50 - std::thread::local::LocalKey<T>::with::hc02698f8f289735c
  17:     0x55c0dc5efa6c - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h97052278c7aa38fb
  18:     0x55c0dc60519f - std::sys_common::backtrace::__rust_begin_short_backtrace::h54d02e0626264f8d
  19:     0x55c0dc6065a1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf1d4ccfc0e2a8cde
  20:     0x55c0dc6257ef - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  21:     0x55c0dc626c8c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13f473dbcdaa0fef
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  22:     0x55c0dc626c8c - std::sys_common::thread::start_thread::h562a7c4953cb1d31
                               at src/libstd/sys_common/thread.rs:13
  23:     0x55c0dc626c8c - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
                               at src/libstd/sys/unix/thread.rs:79
  24:     0x7f44a9343182 - start_thread
  25:     0x7f44a9252b1f - __clone
  26:                0x0 - <unknown>
Expect the event to not close
```
`uname -srv` output:
`Linux 5.0.0-32-generic #34-Ubuntu SMP Wed Oct 2 02:06:48 UTC 2019`
