### ISSUE TITLE
Error: The system just failed to compute an appropriate instant.

### ISSUE THREAD

**Issue by jbax** [input-output-hk/jormungandr#982]
I just upgraded to version 6.1 and ran it using the configuration sample provided in https://iohk.zendesk.com/hc/en-us/articles/360036898153:

```
log:
 format: plain
 level: info
 output: stderr
p2p:
 trusted_peers:
   - address: "/ip4/3.115.194.22/tcp/3000"
     id: ed25519_pk1npsal4j9p9nlfs0fsmfjyga9uqk5gcslyuvxy6pexxr0j34j83rsf98wl2
   - address: "/ip4/13.113.10.64/tcp/3000"
     id: ed25519_pk16pw2st5wgx4558c6temj8tzv0pqc37qqjpy53fstdyzwxaypveys3qcpfl
   - address: "/ip4/52.57.214.174/tcp/3000"
     id: ed25519_pk1v4cj0edgmp8f2m5gex85jglrs2ruvu4z7xgy8fvhr0ma2lmyhtyszxtejz
   - address: "/ip4/3.120.96.93/tcp/3000"
     id: ed25519_pk10gmg0zkxpuzkghxc39n3a646pdru6xc24rch987cgw7zq5pmytmszjdmvh
   - address: "/ip4/52.28.134.8/tcp/3000"
     id: ed25519_pk1unu66eej6h6uxv4j4e9crfarnm6jknmtx9eknvq5vzsqpq6a9vxqr78xrw
   - address: "/ip4/13.52.208.132/tcp/3000"
     id: ed25519_pk15ppd5xlg6tylamskqkxh4rzum26w9acph8gzg86w4dd9a88qpjms26g5q9
   - address: "/ip4/54.153.19.202/tcp/3000"
     id: ed25519_pk1j9nj2u0amlg28k27pw24hre0vtyp3ge0xhq6h9mxwqeur48u463s0crpfk
rest:
 listen: 127.0.0.1:3101
storage: "./storage"
```

The node was started with:
```
RUST_BACKTRACE=full ./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
```

As seen below, after a few minutes the node crashed with the following stack trace:

```
Oct 18 18:19:56.453 INFO Starting jormungandr 0.6.1 (HEAD-a0de8d4, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Oct 18 18:19:56.454 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Oct 18 18:19:56.454 INFO storing blockchain in '"./storage/blocks.sqlite"', task: init
Oct 18 18:19:56.456 INFO connecting to bootstrap peer 3.115.194.22:3000, peer_addr: 3.115.194.22:3000, task: bootstrap
Oct 18 18:44:04.188 INFO switching to new candidate branch, peer_addr: 3.115.194.22:3000, task: bootstrap
Oct 18 18:44:04.196 INFO initial bootstrap completed, peer_addr: 3.115.194.22:3000, task: bootstrap
Oct 18 18:44:04.196 INFO starting task, task: client-query
Oct 18 18:44:04.197 INFO adding P2P Topology module: trusted-peers, task: network
Oct 18 18:44:04.197 INFO connecting to initial gossip peer, peer_addr: 52.57.214.174:3000, task: network
Oct 18 18:44:04.197 INFO connecting to initial gossip peer, peer_addr: 54.153.19.202:3000, task: network
Oct 18 18:44:04.197 INFO connecting to initial gossip peer, peer_addr: 3.115.194.22:3000, task: network
thread 'leadership1' panicked at 'Oct 18 18:44:04.197not yet implemented: The system just failed to compute an appropriate instant.
This could be due to a system suspension or hibernation, in order not to miss out on future
leader elections please prevent your system from suspending or hibernating.
',  jormungandr/src/leadership/mod.rs:183:17
stack backtrace:
CRIT system recorded a 1230s delay. This could be due to a system suspension or hibernation, in order not to miss out on future leader elections please prevent your system from suspending or hibernating., epoch: 237, reason: second time provided was later than self, slot_system_time: 2019-10-18T07:53:34+00:00, now: 2019-10-18T08:14:04.197953472+00:00, task: leadership
Oct 18 18:44:04.198 INFO Starting 1 workers, scope: global
Oct 18 18:44:04.198 INFO connecting to initial gossip peer, peer_addr: 13.52.208.132:3000, task: network
Oct 18 18:44:04.198 INFO Starting server on 127.0.0.1:3101, scope: global
   0:     0x555744694f58 - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x555744694f58 - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x555744694f58 - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x555744694f58 - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x555744694f58 - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x5557446946a7 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x5557446946a7 - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x5557446941cf - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x55574469417c - std::panicking::begin_panic_fmt::hc33ce01c7f7cd52d
                               at src/libstd/panicking.rs:339
   9:     0x5557442eed8c - futures::future::chain::Chain<A,B,C>::poll::h27f95323f58f2f6d
  10:     0x555744705b1b - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h3711bd19806ddeb8
  11:     0x555744689bb0 - futures::task_impl::std::set::he6c155cd71518697
  12:     0x555744685ba9 - tokio_threadpool::worker::Worker::run_task::h1a928c93437110f5
  13:     0x555744685128 - tokio_threadpool::worker::Worker::run::h127f571d23884c72
  14:     0x55574466ad50 - std::thread::local::LocalKey<T>::with::hc02698f8f289735c
  15:     0x55574466ca6c - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h97052278c7aa38fb
  16:     0x55574468219f - std::sys_common::backtrace::__rust_begin_short_backtrace::h54d02e0626264f8d
  17:     0x5557446835a1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf1d4ccfc0e2a8cde
  18:     0x5557446a27ef - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  19:     0x5557446a3c8c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13f473dbcdaa0fef
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  20:     0x5557446a3c8c - std::sys_common::thread::start_thread::h562a7c4953cb1d31
                               at src/libstd/sys_common/thread.rs:13
  21:     0x5557446a3c8c - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
                               at src/libstd/sys/unix/thread.rs:79
  22:     0x7f07633894cf - start_thread
  23:     0x7f076329e2d3 - clone
  24:                0x0 - <unknown>
not yet implemented: The system just failed to compute an appropriate instant.
This could be due to a system suspension or hibernation, in order not to miss out on future
leader elections please prevent your system from suspending or hibernating.
```

Notice the computer did not sleep/hibernate. I was using it the whole time.

My details:
```
jcli 0.6.1 (HEAD-a0de8d4, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jormungandr 0.6.1 (HEAD-a0de8d4, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

Running on Manjaro Linux 64bit.
```
